source('a_std.R')
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'any'))
Generic <- function(x) x |> struct(c('Generic', 'Generic', 'any'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'any'))
Array0 <- function(x) x |> struct(c('Array0', 'Array0', 'any'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'any'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'any'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'any'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'any'))
Function0 <- function(x) x |> struct(c('Function0', 'Function0', 'any'))
Empty0 <- function(x) x |> struct(c('Empty0', 'Empty0', 'any'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'any'))
Integer <- function(x) x |> struct(c('Integer', 'integer', 'any'))
Character <- function(x) x |> struct(c('Character', 'character', 'any'))
Number <- function(x) x |> struct(c('Number', 'numeric', 'any'))
Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'any'))


7L |> Integer()