source('a_std.R')
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Array1 <- function(x) x |> struct(c('Array1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Empty0 <- function(x) x |> struct(c('Empty0', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Array0 <- function(x) x |> struct(c('Array0', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function0 <- function(x) x |> struct(c('Function0', 'Any'))
Generic <- function(x) x |> struct(c('Generic', 'Any'))
Integer <- function(x) x |> struct(c('Integer', 'integer', 'Any'))
Character <- function(x) x |> struct(c('Character', 'character', 'Any'))
Number <- function(x) x |> struct(c('Number', 'numeric', 'Any'))
Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Any'))list__files <- function(x, ...) UseMethod('list__files', x)
file__rename <- function(x, ...) UseMethod('file__rename', x)
dir <- function(x, ...) UseMethod('dir', x)
dir__create <- function(x, ...) UseMethod('dir__create', x)
sum <- function(x, ...) UseMethod('sum', x)
expect_false <- function(x, ...) UseMethod('expect_false', x)
file__copy <- function(x, ...) UseMethod('file__copy', x)
reduce <- function(x, ...) UseMethod('reduce', x)
file__exists <- function(x, ...) UseMethod('file__exists', x)
file__create <- function(x, ...) UseMethod('file__create', x)
getwd <- function(x, ...) UseMethod('getwd', x)
expect_equal <- function(x, ...) UseMethod('expect_equal', x)
setwd <- function(x, ...) UseMethod('setwd', x)
file__remove <- function(x, ...) UseMethod('file__remove', x)
unlink <- function(x, ...) UseMethod('unlink', x)


