getwd <- function(x, ...) UseMethod('getwd', x)
dir__create <- function(x, ...) UseMethod('dir__create', x)
unlink <- function(x, ...) UseMethod('unlink', x)
file__remove <- function(x, ...) UseMethod('file__remove', x)
expect_equal <- function(x, ...) UseMethod('expect_equal', x)
reduce <- function(x, ...) UseMethod('reduce', x)
sum <- function(x, ...) UseMethod('sum', x)
setwd <- function(x, ...) UseMethod('setwd', x)
file__rename <- function(x, ...) UseMethod('file__rename', x)
file__exists <- function(x, ...) UseMethod('file__exists', x)
dir <- function(x, ...) UseMethod('dir', x)
file__copy <- function(x, ...) UseMethod('file__copy', x)
file__create <- function(x, ...) UseMethod('file__create', x)
expect_false <- function(x, ...) UseMethod('expect_false', x)
plot <- function(x, ...) UseMethod('plot', x)
list__files <- function(x, ...) UseMethod('list__files', x)
- function(x, ...) UseMethod('plot', x)
file__exists', x)
