Function1 <- function(x) x |> struct(c('Function1', 'Generic', 'Any'))
Function0 <- function(x) x |> struct(c('Function0', 'Any', 'Generic'))
Plot <- function(x) x |> struct(c('Plot', 'Generic', 'Any'))
Function17 <- function(x) x |> struct(c('Function17', 'Any', 'Generic'))
Tag0 <- function(x) x |> struct(c('Tag0', 'Any', 'Generic'))
Array3 <- function(x) x |> struct(c('Array3', 'Generic', 'Any'))
Array2 <- function(x) x |> struct(c('Array2', 'Any', 'Generic'))
Function16 <- function(x) x |> struct(c('Function16', 'Generic', 'Any'))
Function15 <- function(x) x |> struct(c('Function15', 'Function0', 'Generic', 'Any'))
Function14 <- function(x) x |> struct(c('Function14', 'Generic', 'Any'))
Array1 <- function(x) x |> struct(c('Array1', 'Generic', 'Any'))
Function13 <- function(x) x |> struct(c('Function13', 'Function0', 'Generic', 'Any'))
Function12 <- function(x) x |> struct(c('Function12', 'Generic', 'Any'))
Function11 <- function(x) x |> struct(c('Function11', 'Generic', 'Any'))
Function10 <- function(x) x |> struct(c('Function10', 'Any', 'Function0', 'Generic'))
Function9 <- function(x) x |> struct(c('Function9', 'Any', 'Generic'))
Function8 <- function(x) x |> struct(c('Function8', 'Any', 'Function0', 'Generic'))
Function7 <- function(x) x |> struct(c('Function7', 'Any', 'Generic'))
Function6 <- function(x) x |> struct(c('Function6', 'Generic', 'Any'))
Function5 <- function(x) x |> struct(c('Function5', 'Function0', 'Generic', 'Any'))
Empty0 <- function(x) x |> struct(c('Empty0', 'integer', 'Any', 'Function0', 'Function1', 'Function0', 'Generic'))
Function4 <- function(x) x |> struct(c('Function4', 'Generic', 'Function0', 'Any'))
Function3 <- function(x) x |> struct(c('Function3', 'Any', 'Generic'))
Array0 <- function(x) x |> struct(c('Array0', 'Generic', 'Any'))
Function2 <- function(x) x |> struct(c('Function2', 'Generic', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Generic', 'Any'))
Function0 <- function(x) x |> struct(c('Function0', 'Any', 'Generic'))
Generic <- function(x) x |> struct(c('Generic', 'Any'))
Integer <- function(x) x |> struct(c('Integer', 'integer', 'Any', 'Generic'))
Character <- function(x) x |> struct(c('Character', 'character', 'Any', 'Generic'))
Number <- function(x) x |> struct(c('Number', 'numeric', 'Any', 'Generic'))
Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Generic', 'Any'))