Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'Any'))
Addable <- function(x) x |> struct(c('Addable', 'Addable', 'Any'))
Array0 <- function(x) x |> struct(c('Array0', 'Array0', 'Any', 'Addable'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'Any'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'Any'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'Any'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'Any'))
Function2 <- function(x) x |> struct(c('Function2', 'Function2', 'Any'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'Any'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'Any'))
Function3 <- function(x) x |> struct(c('Function3', 'Function3', 'Any'))
Empty0 <- function(x) x |> struct(c('Empty0', 'Empty0', 'Addable', 'Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Function1', 'Any'))
Function0 <- function(x) x |> struct(c('Function0', 'Function0', 'Any'))
Generic <- function(x) x |> struct(c('Generic', 'Generic', 'Any'))
Integer <- function(x) x |> struct(c('Integer', 'integer', 'Addable', 'Any'))
Character <- function(x) x |> struct(c('Character', 'character', 'Any'))
Number <- function(x) x |> struct(c('Number', 'numeric', 'Any', 'Addable'))
Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Any'))