as.Function0 <- function(x) x |> struct(c('Function0', 'Any'))
as.Foreign <- function(x) x |> struct(c('Foreign', 'Any', 'None'))
as.Function66 <- function(x) x |> struct(c('Function66', 'Any'))
as.State0 <- function(x) x |> struct(c('State0', 'Any'))
as.State <- function(x) x |> struct(c('State', 'Any', 'None'))
as.Function61 <- function(x) x |> struct(c('Function61', 'Any'))
as.Function60 <- function(x) x |> struct(c('Function60', 'Any'))
as.Factor0 <- function(x) x |> struct(c('Factor0', 'Any'))
as.Factor <- function(x) x |> struct(c('Factor', 'integer', 'Any'))
as.Function50 <- function(x) x |> struct(c('Function50', 'Any'))
as.Union0 <- function(x) x |> struct(c('Union0', 'Any'))
as.Function45 <- function(x) x |> struct(c('Function45', 'Any'))
as.Function44 <- function(x) x |> struct(c('Function44', 'Any'))
as.Function41 <- function(x) x |> struct(c('Function41', 'Any'))
as.Function40 <- function(x) x |> struct(c('Function40', 'Any'))
as.Function39 <- function(x) x |> struct(c('Function39', 'Any'))
as.Array3 <- function(x) x |> struct(c('Array3', 'integer', 'Any'))
as.Iterable <- function(x) x |> struct(c('Iterable', 'Any'))
as.Function26 <- function(x) x |> struct(c('Function26', 'Any'))
as.Function25 <- function(x) x |> struct(c('Function25', 'Any'))
as.Function24 <- function(x) x |> struct(c('Function24', 'Any'))
as.Tag0 <- function(x) x |> struct(c('Tag0', 'Any'))
as.Function21 <- function(x) x |> struct(c('Function21', 'Any'))
as.Function20 <- function(x) x |> struct(c('Function20', 'Any'))
as.Function19 <- function(x) x |> struct(c('Function19', 'Any'))
as.Function18 <- function(x) x |> struct(c('Function18', 'Any'))
as.Function17 <- function(x) x |> struct(c('Function17', 'Any'))
as.Function16 <- function(x) x |> struct(c('Function16', 'Any'))
as.Function14 <- function(x) x |> struct(c('Function14', 'Any'))
as.Function12 <- function(x) x |> struct(c('Function12', 'Any'))
as.Function11 <- function(x) x |> struct(c('Function11', 'Any'))
as.Function5 <- function(x) x |> struct(c('Function5', 'Any'))
as.Empty0 <- function(x) x |> struct(c('Empty0', 'Todo', 'Function0', 'Any'))
as.Function4 <- function(x) x |> struct(c('Function4', 'Any'))
as.Function2 <- function(x) x |> struct(c('Function2', 'Any'))
as.Function1 <- function(x) x |> struct(c('Function1', 'Any'))
as.Function0 <- function(x) x |> struct(c('Function0', 'Any'))
as.Integer <- function(x) x |> struct(c('Integer', 'integer', 'Any'))
as.Character <- function(x) x |> struct(c('Character', 'character', 'Any'))
as.Number <- function(x) x |> struct(c('Number', 'numeric', 'Any'))
as.Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Any'))