as.Function58 <- function(x) x |> struct(c('Function58', 'Any'))
as.State0 <- function(x) x |> struct(c('State0', 'Any'))
as.State <- function(x) x |> struct(c('State', 'Any', 'None'))
as.Function53 <- function(x) x |> struct(c('Function53', 'Any'))
as.Function52 <- function(x) x |> struct(c('Function52', 'Any'))
as.Factor0 <- function(x) x |> struct(c('Factor0', 'Any'))
as.Factor <- function(x) x |> struct(c('Factor', 'integer', 'Any'))
as.Array4 <- function(x) x |> struct(c('Array4', 'Any'))
as.Function37 <- function(x) x |> struct(c('Function37', 'Any'))
as.Function36 <- function(x) x |> struct(c('Function36', 'Any'))
as.Function33 <- function(x) x |> struct(c('Function33', 'Any'))
as.Function32 <- function(x) x |> struct(c('Function32', 'Any'))
as.Function31 <- function(x) x |> struct(c('Function31', 'Any'))
as.Array3 <- function(x) x |> struct(c('Array3', 'Any'))
as.Iterable <- function(x) x |> struct(c('Iterable', 'Any'))
as.Function20 <- function(x) x |> struct(c('Function20', 'Any'))
as.Function19 <- function(x) x |> struct(c('Function19', 'Any'))
as.Function18 <- function(x) x |> struct(c('Function18', 'Any'))
as.Tag0 <- function(x) x |> struct(c('Tag0', 'Any'))
as.Function15 <- function(x) x |> struct(c('Function15', 'Any'))
as.Function14 <- function(x) x |> struct(c('Function14', 'Any'))
as.Function13 <- function(x) x |> struct(c('Function13', 'Any'))
as.Function11 <- function(x) x |> struct(c('Function11', 'Any'))
as.Function10 <- function(x) x |> struct(c('Function10', 'Any'))
as.Function5 <- function(x) x |> struct(c('Function5', 'Any'))
as.Empty0 <- function(x) x |> struct(c('Empty0', 'Any'))
as.Function4 <- function(x) x |> struct(c('Function4', 'Any'))
as.Function2 <- function(x) x |> struct(c('Function2', 'Any'))
as.Function1 <- function(x) x |> struct(c('Function1', 'Any'))
as.Function0 <- function(x) x |> struct(c('Function0', 'Any'))
as.Integer <- function(x) x |> struct(c('Integer', 'integer', 'Any'))
as.Character <- function(x) x |> struct(c('Character', 'character', 'Any'))
as.Number <- function(x) x |> struct(c('Number', 'numeric', 'Any'))
as.Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Any'))