//! MCP server exposing the TypR compiler to AI agents.
//!
//! Runs over stdio (wired as the `typr mcp` subcommand — never an
//! `npx`/`sh -c` one-liner, see the crate-level design notes) and offers
//! `check` (type-check only) and `build` (transpile to R) tools, both
//! in-process: no filesystem, no project directory, no `.typr_cache`. They
//! reuse the same inlined-context recipe as `typr-wasm`'s `compile`/
//! `typeCheck` (the browser playground), which is the proof this works
//! without I/O.
//!
//! It also serves read-only **resources**, kept in-process the same way
//! `STD_R` is: a vendored snapshot (`data/*.md`, `include_str!`'d below), not
//! a live fetch from the docs site. **These snapshots must be refreshed by
//! hand** (`cp` from `typr.github.io/docs/...`) whenever the source page
//! changes — there is no CI check tying the two repos together yet.
//!
//! `typr://lexicon` and `typr://operators` are the generated reference
//! tables published at `typr.github.io/docs/reference/{lexicon,operators}.md`
//! (themselves regenerated there by `npm run syntax:reference`), so an agent
//! that hits an unfamiliar sigil or operator in a `check`/`build` diagnostic
//! (say `?B` or `|>`) can look it up without leaving the MCP session or
//! guessing.
//!
//! `typr://pitfalls`, `typr://escape-hatches` and `typr://cheatsheet` are
//! aimed the other direction: not "what does this diagnostic mean" but "how
//! do I write this idiomatically" — known parser gotchas
//! (`docs/concepts/known-pitfalls.md`), the sanctioned ways to drop out of
//! the type system (`docs/reference/escape-hatches.md`), and a side-by-side
//! R/TypR comparison (`docs/reference/cheatsheet.md`).
//!
//! A third tool, `explain`, takes a diagnostic `code` (`T0xx`/`S0xx`, as
//! returned by `check`/`build`) and returns a longer explanation plus a
//! minimal before/after example, for every code in [`explain::ENTRIES`] —
//! see that module's docs for the handful of declared-but-dead codes it
//! doesn't (and can't) cover.
//!
//! Type checking is recursive, so a long-lived server must drive it from a
//! large-stack thread — see [`run_stdio`].
//!
//! ## Client configuration
//!
//! Point an MCP client at the `typr` binary with the `mcp` argument. After
//! `cargo install typr`, that's just:
//!
//! ```json
//! {
//!   "mcpServers": {
//!     "typr": {
//!       "command": "typr",
//!       "args": ["mcp"]
//!     }
//!   }
//! }
//! ```
//!
//! Building from a local checkout instead? Point `command` at
//! `target/debug/typr` (or `target/release/typr`).

use rmcp::handler::server::wrapper::{Json, Parameters};
use rmcp::model::{
    ListResourcesResult, PaginatedRequestParams, ReadResourceRequestParams, ReadResourceResponse, ReadResourceResult,
    Resource, ResourceContents, ServerCapabilities, ServerInfo,
};
use rmcp::service::{RequestContext, RoleServer};
use rmcp::transport::stdio;
use rmcp::ErrorData as McpError;
use rmcp::{tool, tool_handler, tool_router, ServerHandler, ServiceExt};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

mod explain;

use typr_core::components::context::config::{Config, Environment};
use typr_core::components::error_message::syntax_error::SyntaxError;
use typr_core::components::error_message::type_error::TypeError;
use typr_core::components::error_message::typr_error::TypRError;
use typr_core::parsing::parse_from_string_with_errors;
use typr_core::processes::type_checking::type_checker::TypeChecker;

/// Standard library R code (embedded at compile time): a vendored copy of
/// `typr-cli/configs/src/std.R`, same source `typr-wasm` inlines into its
/// `compile()` output. Vendored (rather than `include_str!`'d across the
/// crate boundary like `typr-wasm` does) because `cargo publish` packages
/// each crate in isolation and can't reach a sibling crate's files —
/// `tests::vendored_std_r_matches_typr_cli` catches drift between the two
/// copies whenever `cargo test --workspace` runs in the full checkout.
const STD_R: &str = include_str!("../data/std.R");

/// Vendored snapshot of `typr.github.io/docs/reference/lexicon.md` — see the
/// resync note in the crate-level docs above.
const LEXICON_MD: &str = include_str!("../data/lexicon.md");

/// Vendored snapshot of `typr.github.io/docs/reference/operators.md` — see
/// the resync note in the crate-level docs above.
const OPERATORS_MD: &str = include_str!("../data/operators.md");

/// Vendored snapshot of the stdlib markdown digest, generated by
/// `typr std doc --format md --output crates/typr-mcp/data/stdlib.md`.
/// Refresh by re-running that command after any change to `configs/std/*.ty`.
const STDLIB_MD: &str = include_str!("../data/stdlib.md");

/// Vendored snapshot of `typr.github.io/docs/concepts/known-pitfalls.md`.
const PITFALLS_MD: &str = include_str!("../data/pitfalls.md");

/// Vendored snapshot of `typr.github.io/docs/reference/escape-hatches.md`.
const ESCAPE_HATCHES_MD: &str = include_str!("../data/escape-hatches.md");

/// Vendored snapshot of `typr.github.io/docs/reference/cheatsheet.md`.
const CHEATSHEET_MD: &str = include_str!("../data/cheatsheet.md");

/// Index of every page on `typr.github.io/docs/` (title, Diátaxis category,
/// one-line description, canonical URL) — generated from each page's
/// frontmatter, not hand-typed. Unlike the other vendored snapshots this one
/// has no full page content, only enough to route a question to the right
/// URL; [`search_docs`] parses it at request time. Regenerate with the
/// one-off script noted in that function's docs whenever a page is added,
/// removed, or its title/description frontmatter changes.
const DOCS_INDEX_MD: &str = include_str!("../data/docs-index.md");

const LEXICON_URI: &str = "typr://lexicon";
const OPERATORS_URI: &str = "typr://operators";
const STDLIB_URI: &str = "typr://stdlib";
const PITFALLS_URI: &str = "typr://pitfalls";
const ESCAPE_HATCHES_URI: &str = "typr://escape-hatches";
const CHEATSHEET_URI: &str = "typr://cheatsheet";
const DOCS_INDEX_URI: &str = "typr://docs-index";

fn syntax_resources() -> Vec<Resource> {
    vec![
        Resource::new(LEXICON_URI, "lexicon")
            .with_title("Lexicon & Literals")
            .with_description(
                "TypR's literals, identifier casing rules, and the full reserved-word table \
                 (keywords, annotations, primitive/built-in types, kind sigils), generated \
                 from the compiler's syntax manifest.",
            )
            .with_mime_type("text/markdown"),
        Resource::new(OPERATORS_URI, "operators")
            .with_title("Operators & Precedence")
            .with_description(
                "Every TypR operator, grouped by role, plus the four-level precedence table \
                 (member access/pipe binds tighter than arithmetic, unlike most languages), \
                 generated from the compiler's syntax manifest.",
            )
            .with_mime_type("text/markdown"),
        Resource::new(STDLIB_URI, "stdlib")
            .with_title("Standard Library Signatures")
            .with_description(
                "Typed signatures for the R standard library (base, stats, utils) and TypR's \
                 own built-in functions, grouped by package. Includes tier badges (T1=compiler, \
                 T2=doc), parameter docs, and one example per function.",
            )
            .with_mime_type("text/markdown"),
        Resource::new(PITFALLS_URI, "pitfalls")
            .with_title("Known Pitfalls")
            .with_description(
                "Common parser pitfalls and ambiguities (semicolon swallowing, '//' not being \
                 a comment, single '=' never being a comparison, record vs tuple shape rules, \
                 minimum type-alias name length) plus a style rule: alias a structural type as \
                 soon as it appears in a function's first parameter. Worth a read before \
                 writing TypR, not just after a diagnostic.",
            )
            .with_mime_type("text/markdown"),
        Resource::new(ESCAPE_HATCHES_URI, "escape-hatches")
            .with_title("Escape Hatches")
            .with_description(
                "The sanctioned ways to drop out of TypR's type system to write raw R or \
                 JavaScript ('extern', untyped 'function(...)' values, 'R { }' blocks) — what \
                 each one checks and what it doesn't, so an agent reaches for the right one \
                 instead of the bluntest one.",
            )
            .with_mime_type("text/markdown"),
        Resource::new(CHEATSHEET_URI, "cheatsheet")
            .with_title("TypR vs R Cheatsheet")
            .with_description(
                "Side-by-side comparison of idiomatic R and idiomatic TypR across syntax, \
                 typing, naming, sum types, dispatch, interfaces and pattern matching — useful \
                 for writing TypR that looks like TypR instead of R with type annotations \
                 bolted on.",
            )
            .with_mime_type("text/markdown"),
        Resource::new(DOCS_INDEX_URI, "docs-index")
            .with_title("Documentation Index")
            .with_description(
                "Every page on typr.github.io/docs/ with its title, category, one-line \
                 description and URL — for browsing the full table at once. Prefer the \
                 `docs_search` tool to find a specific page by keyword.",
            )
            .with_mime_type("text/markdown"),
    ]
}

fn read_syntax_resource(uri: &str) -> Result<ReadResourceResult, McpError> {
    let text = match uri {
        LEXICON_URI => LEXICON_MD,
        OPERATORS_URI => OPERATORS_MD,
        STDLIB_URI => STDLIB_MD,
        PITFALLS_URI => PITFALLS_MD,
        ESCAPE_HATCHES_URI => ESCAPE_HATCHES_MD,
        CHEATSHEET_URI => CHEATSHEET_MD,
        DOCS_INDEX_URI => DOCS_INDEX_MD,
        _ => {
            return Err(McpError::invalid_params(format!("unknown resource uri: {uri}"), None));
        }
    };
    Ok(ReadResourceResult::new(vec![
        ResourceContents::text(text, uri).with_mime_type("text/markdown")
    ]))
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct CheckParams {
    /// TypR source code to type-check.
    pub source: String,
}

#[derive(Debug, Serialize, JsonSchema)]
pub struct Diagnostic {
    /// Stable error code (`T0xx` for type errors, `S0xx` for syntax errors) —
    /// see `TypeError::code`/`SyntaxError::code` in typr-core.
    pub code: String,
    pub message: String,
}

#[derive(Debug, Serialize, JsonSchema)]
pub struct CheckResult {
    pub ok: bool,
    pub diagnostics: Vec<Diagnostic>,
}

/// Turn a `catch_unwind` payload into a `Diagnostic`.
///
/// The parser raises a handful of syntax errors via `std::panic::panic_any`
/// instead of the recoverable `push_parse_error` path (`FunctionWithoutType`,
/// `FunctionWithoutReturnType` in `parsing/elements.rs`; a `TypeError::WrongExpression`
/// in `parsing/operation_priority.rs`) — same two call sites `typr-cli`'s
/// `standard_library.rs` already has to work around. `check`/`build` must
/// never let one of these escape as an unhandled panic: unlike the CLI's
/// batch tooling, this runs in a long-lived server process where a crash
/// takes down every in-flight request, not just the offending one.
fn panic_payload_diagnostic(payload: Box<dyn std::any::Any + Send>) -> Diagnostic {
    if let Some(e) = payload.downcast_ref::<SyntaxError>() {
        return Diagnostic {
            code: e.code().to_string(),
            message: e.simple_message(),
        };
    }
    if let Some(e) = payload.downcast_ref::<TypeError>() {
        return Diagnostic {
            code: e.code().to_string(),
            message: e.simple_message(),
        };
    }
    let message = payload
        .downcast_ref::<&str>()
        .map(|s| s.to_string())
        .or_else(|| payload.downcast_ref::<String>().cloned())
        .unwrap_or_else(|| "internal parser error".to_string());
    Diagnostic {
        code: "S000".to_string(),
        message,
    }
}

fn check_source(source: &str) -> CheckResult {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| check_source_inner(source))) {
        Ok(result) => result,
        Err(payload) => CheckResult {
            ok: false,
            diagnostics: vec![panic_payload_diagnostic(payload)],
        },
    }
}

fn check_source_inner(source: &str) -> CheckResult {
    let parsed = parse_from_string_with_errors(source, "main.ty");
    if parsed.has_errors() {
        let diagnostics = parsed
            .errors
            .into_iter()
            .map(|e| {
                let err = TypRError::syntax_error(e);
                Diagnostic {
                    code: err.code().to_string(),
                    message: err.simple_message(),
                }
            })
            .collect();
        return CheckResult { ok: false, diagnostics };
    }

    // Same Environment::Wasm context typr-wasm's type_check() builds: all
    // modules inlined, no source() calls, nothing read from disk.
    let context = Config::default().set_environment(Environment::Wasm).to_context();
    let type_checker = TypeChecker::new(context).typing_no_panic(&parsed.ast);

    let diagnostics = type_checker
        .get_errors()
        .iter()
        .map(|e| Diagnostic {
            code: e.code().to_string(),
            message: e.simple_message(),
        })
        .collect();

    CheckResult {
        ok: !type_checker.has_errors(),
        diagnostics,
    }
}

#[derive(Debug, Serialize, JsonSchema)]
pub struct BuildResult {
    pub ok: bool,
    /// Generated R code, with the standard library, type annotations, and
    /// generic function dispatchers inlined — produced even when
    /// `diagnostics` is non-empty (best-effort transpilation, same as
    /// `typr-wasm`'s `compile()`).
    pub r_code: String,
    pub diagnostics: Vec<Diagnostic>,
}

fn build_source(source: &str) -> BuildResult {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| build_source_inner(source))) {
        Ok(result) => result,
        Err(payload) => BuildResult {
            ok: false,
            r_code: String::new(),
            diagnostics: vec![panic_payload_diagnostic(payload)],
        },
    }
}

fn build_source_inner(source: &str) -> BuildResult {
    let parsed = parse_from_string_with_errors(source, "main.ty");
    if parsed.has_errors() {
        let diagnostics = parsed
            .errors
            .into_iter()
            .map(|e| {
                let err = TypRError::syntax_error(e);
                Diagnostic {
                    code: err.code().to_string(),
                    message: err.simple_message(),
                }
            })
            .collect();
        return BuildResult {
            ok: false,
            r_code: String::new(),
            diagnostics,
        };
    }

    // Same Environment::Wasm context check_source() builds.
    let context = Config::default().set_environment(Environment::Wasm).to_context();
    let type_checker = TypeChecker::new(context).typing_no_panic(&parsed.ast);

    let diagnostics: Vec<Diagnostic> = type_checker
        .get_errors()
        .iter()
        .map(|e| Diagnostic {
            code: e.code().to_string(),
            message: e.simple_message(),
        })
        .collect();
    let ok = !type_checker.has_errors();

    // Transpile proceeds even with type errors (best-effort output), mirroring
    // typr-wasm's compile().
    let context = type_checker.get_context();
    let main_code = type_checker.transpile();
    let type_annotations = context.get_type_anotations();
    let generic_functions: String = context
        .get_all_generic_functions()
        .iter()
        .map(|(var, _)| var.get_name())
        .filter(|x| !x.contains("<-"))
        .map(|fn_name| {
            format!(
                "{} <- function(x, ...) UseMethod('{}', x)",
                fn_name,
                fn_name.replace("`", "")
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let mut r_code = String::new();
    r_code.push_str("# === TypR Standard Library ===\n");
    r_code.push_str(STD_R);
    r_code.push_str("\n\n");
    if !generic_functions.trim().is_empty() {
        r_code.push_str("# === Generic Functions ===\n");
        r_code.push_str(&generic_functions);
        r_code.push_str("\n\n");
    }
    if !type_annotations.trim().is_empty() {
        r_code.push_str("# === Type Annotations ===\n");
        r_code.push_str(&type_annotations);
        r_code.push_str("\n\n");
    }
    r_code.push_str("# === Main Code ===\n");
    r_code.push_str(&main_code);

    BuildResult {
        ok,
        r_code,
        diagnostics,
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ExplainParams {
    /// Diagnostic code to explain, e.g. "T001" or "S003" — the `code` field
    /// of a `check`/`build` diagnostic.
    pub code: String,
}

#[derive(Debug, Serialize, JsonSchema)]
pub struct ExplainResult {
    pub code: String,
    /// False if `code` isn't covered — practically only the handful of
    /// declared-but-dead codes `check`/`build` can never actually produce
    /// (see `explain::ENTRIES`'s module docs). The other fields are then
    /// absent; fall back to the diagnostic's own `message` from
    /// `check`/`build` in that case.
    pub found: bool,
    pub title: Option<String>,
    pub explanation: Option<String>,
    /// Minimal TypR source that reproduces this diagnostic.
    pub bad_example: Option<String>,
    /// The same source, fixed — type-checks cleanly.
    pub good_example: Option<String>,
}

fn explain_code(code: &str) -> ExplainResult {
    match explain::find(code) {
        Some(e) => ExplainResult {
            code: e.code.to_string(),
            found: true,
            title: Some(e.title.to_string()),
            explanation: Some(e.explanation.to_string()),
            bad_example: Some(e.bad.to_string()),
            good_example: Some(e.good.to_string()),
        },
        None => ExplainResult {
            code: code.to_string(),
            found: false,
            title: None,
            explanation: None,
            bad_example: None,
            good_example: None,
        },
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct DocsSearchParams {
    /// Free-text query, e.g. "dplyr", "how do I embed a type", "match exhaustive".
    /// Matched case-insensitively, word by word, against each page's title,
    /// category, and description.
    pub query: String,
}

#[derive(Debug, Serialize, JsonSchema, PartialEq, Eq)]
pub struct DocMatch {
    pub title: String,
    /// Diátaxis category: Tutorial, How-To, Reference, Philosophy, or Deep Dive.
    pub category: String,
    pub description: String,
    pub url: String,
}

#[derive(Debug, Serialize, JsonSchema)]
pub struct DocsSearchResult {
    /// Up to 8 pages, best match first. Empty means no page's title,
    /// category or description contains any word of the query — try a
    /// broader or different term, or fall back to `typr://docs-index` to
    /// browse the full table.
    pub matches: Vec<DocMatch>,
}

/// One row of the vendored `docs-index.md` table.
struct DocPage {
    title: String,
    category: String,
    description: String,
    url: String,
}

/// Split a `| a | b | c | d |` table row into its four cells, unescaping the
/// `\|` this table uses for a literal pipe inside a cell (see the generator
/// script noted below). Skips the header and `|---|---|---|---|` separator
/// rows, which have no ordinary characters between the pipes.
fn parse_docs_index() -> Vec<DocPage> {
    DOCS_INDEX_MD
        .lines()
        .filter(|line| line.starts_with('|') && !line.starts_with("|---"))
        .filter_map(|line| {
            let cells: Vec<String> = line
                .trim_matches('|')
                .split('|')
                .map(|cell| cell.trim().replace("\\|", "|"))
                .collect();
            match cells.as_slice() {
                [title, category, description, url] if title != "Title" => Some(DocPage {
                    title: title.clone(),
                    category: category.clone(),
                    description: description.clone(),
                    url: url.clone(),
                }),
                _ => None,
            }
        })
        .collect()
}

/// Score a page against a lowercase, whitespace-split query: 3 points per
/// query word found in the title, 1 point per word found in the category or
/// description. A page with no matching word scores 0 and is dropped.
fn score(page: &DocPage, query_words: &[&str]) -> u32 {
    let title = page.title.to_lowercase();
    let category = page.category.to_lowercase();
    let description = page.description.to_lowercase();
    query_words
        .iter()
        .map(|word| {
            let mut s = 0;
            if title.contains(word) {
                s += 3;
            }
            if category.contains(word) || description.contains(word) {
                s += 1;
            }
            s
        })
        .sum()
}

/// Find pages on `typr.github.io/docs/` relevant to a free-text query, so an
/// agent that hits a question `check`/`build`/`explain` and the other
/// resources can't answer (a tutorial's worth of context, design rationale,
/// a how-to for a specific R package) can redirect the user to the right
/// page instead of guessing or staying silent.
///
/// Regenerate `data/docs-index.md` after editing pages on the docs site:
/// there is no build-time link between the two repos, same as every other
/// vendored snapshot here. The generator is a one-off script (not checked
/// in) that reads each page's `title`/`description` frontmatter — see the
/// crate-level docs for the refresh convention; re-run the same script logic
/// if the docs site's page set changes.
fn search_docs(query: &str) -> DocsSearchResult {
    let query_words: Vec<String> = query.to_lowercase().split_whitespace().map(str::to_string).collect();
    let query_words: Vec<&str> = query_words.iter().map(String::as_str).collect();

    let mut scored: Vec<(u32, DocPage)> = parse_docs_index()
        .into_iter()
        .map(|page| (score(&page, &query_words), page))
        .filter(|(s, _)| *s > 0)
        .collect();
    scored.sort_by(|a, b| b.0.cmp(&a.0));

    let matches = scored
        .into_iter()
        .take(8)
        .map(|(_, page)| DocMatch {
            title: page.title,
            category: page.category,
            description: page.description,
            url: page.url,
        })
        .collect();

    DocsSearchResult { matches }
}

#[derive(Clone, Default)]
pub struct TyprMcpServer;

#[tool_router]
impl TyprMcpServer {
    pub fn new() -> Self {
        Self
    }

    #[tool(description = "Type-check TypR source code in-process (no filesystem, no project \
        directory) and report diagnostics with stable error codes (T0xx for type errors, \
        S0xx for syntax errors).")]
    async fn check(&self, Parameters(CheckParams { source }): Parameters<CheckParams>) -> Json<CheckResult> {
        Json(check_source(&source))
    }

    #[tool(
        description = "Transpile TypR source code to R in-process (no filesystem, no project \
        directory), returning the generated R code — with the standard library, type \
        annotations, and generic function dispatchers inlined — plus any diagnostics found \
        while type-checking (stable T0xx/S0xx codes, same as `check`). `r_code` is produced \
        even when type errors are present, so callers should check `ok`/`diagnostics` before \
        trusting the output."
    )]
    async fn build(&self, Parameters(CheckParams { source }): Parameters<CheckParams>) -> Json<BuildResult> {
        Json(build_source(&source))
    }

    #[tool(description = "Explain a TypR diagnostic code (T0xx/S0xx, from a `check`/`build` \
        diagnostic's `code` field) with a longer description of why the compiler rejects it \
        plus a minimal before/after TypR example. Covers every code the compiler can actually \
        produce — `found: false` means this code is declared but dead (unreachable in the \
        current compiler), so fall back to the short `message` `check`/`build` already returned.")]
    async fn explain(&self, Parameters(ExplainParams { code }): Parameters<ExplainParams>) -> Json<ExplainResult> {
        Json(explain_code(&code))
    }

    #[tool(description = "Search typr.github.io/docs/ by keyword and get back matching pages \
        (title, Diátaxis category, one-line description, URL) — for a question `check`/ \
        `build`/`explain` and the other resources can't answer: a tutorial's worth of context, \
        design rationale, or a how-to for a specific R package (dplyr, Shiny, R6...). Redirect \
        the user to the returned URL (or fetch it, if the client has a web tool) rather than \
        guessing at content this server doesn't have. Empty `matches` means no page's title, \
        category or description contains any word of the query — try a broader term or read \
        `typr://docs-index` for the full table.")]
    async fn docs_search(
        &self,
        Parameters(DocsSearchParams { query }): Parameters<DocsSearchParams>,
    ) -> Json<DocsSearchResult> {
        Json(search_docs(&query))
    }
}

#[tool_handler]
impl ServerHandler for TyprMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().enable_resources().build()).with_instructions(
            "TypR compiler tools. `check` type-checks TypR source and returns diagnostics \
             tagged with stable error codes. `build` does the same but also returns the \
             transpiled R code. `explain` takes one of those codes and returns a longer \
             explanation plus a before/after example, for essentially every code the compiler \
             can produce — worth a try after any `check`/`build` diagnostic before guessing at \
             a fix from the short message alone. `docs_search` looks up typr.github.io/docs/ by \
             keyword and returns matching page titles/URLs — reach for it whenever the user's \
             question is broader than a diagnostic (a tutorial, design rationale, a how-to for \
             dplyr/Shiny/R6...) and redirect them to the URL instead of guessing; empty results \
             mean try a different term or browse `typr://docs-index`. Seven resources: \
             `typr://lexicon` and `typr://operators` hold the reference tables for TypR's \
             keywords, sigils and operators — read one when a diagnostic mentions a token whose \
             meaning is unclear. `typr://stdlib` holds typed signatures for the R standard \
             library and TypR's built-in functions, grouped by package with tier badges and \
             examples. `typr://pitfalls`, `typr://escape-hatches` and `typr://cheatsheet` are \
             worth reading before writing TypR, not just after a diagnostic: known parser \
             gotchas, the sanctioned ways to drop out of the type system, and a side-by-side \
             R/TypR comparison — read these to write idiomatic TypR instead of R with type \
             annotations bolted on. `typr://docs-index` lists every page on the docs site with \
             its URL, for browsing the full table `docs_search` searches over.",
        )
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult::with_all_items(syntax_resources()))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, McpError> {
        read_syntax_resource(&request.uri).map(Into::into)
    }
}

#[cfg(test)]
mod tests {
    use super::{
        build_source, check_source, explain, explain_code, parse_docs_index, read_syntax_resource, search_docs,
        syntax_resources, CHEATSHEET_URI, DOCS_INDEX_URI, ESCAPE_HATCHES_URI, LEXICON_URI, OPERATORS_URI, PITFALLS_URI,
        STDLIB_URI,
    };
    use rmcp::model::ResourceContents;

    #[test]
    fn valid_source_has_no_diagnostics() {
        let result = check_source("let x: int <- 42;");
        assert!(result.ok, "{:?}", result.diagnostics);
        assert!(result.diagnostics.is_empty());
    }

    #[test]
    fn type_mismatch_is_reported_with_a_t_code() {
        let result = check_source("let x: int <- \"oops\";");
        assert!(!result.ok);
        assert_eq!(result.diagnostics.len(), 1);
        assert!(
            result.diagnostics[0].code.starts_with('T'),
            "{:?}",
            result.diagnostics[0]
        );
    }

    #[test]
    fn forgotten_semicolon_is_reported_with_an_s_code() {
        let result = check_source("let a <- 5");
        assert!(!result.ok);
        assert_eq!(result.diagnostics.len(), 1);
        assert!(
            result.diagnostics[0].code.starts_with('S'),
            "{:?}",
            result.diagnostics[0]
        );
    }

    /// `data/std.R` is a vendored copy (see [`super::STD_R`]'s doc comment for
    /// why it can't be `include_str!`'d straight from `typr-cli`). This only
    /// catches drift when run from a full checkout — `cargo test --workspace`
    /// in CI, not an isolated `cargo publish` verification build.
    #[test]
    fn vendored_std_r_matches_typr_cli() {
        let canonical = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../typr-cli/configs/src/std.R"
        );
        let canonical = std::fs::read_to_string(canonical).expect("read typr-cli's configs/src/std.R");
        assert_eq!(
            super::STD_R,
            canonical,
            "crates/typr-mcp/data/std.R is out of sync with crates/typr-cli/configs/src/std.R — re-run `cp crates/typr-cli/configs/src/std.R crates/typr-mcp/data/std.R`"
        );
    }

    #[test]
    fn valid_source_transpiles_to_r_with_std_lib_inlined() {
        let result = build_source("let x: int <- 42;");
        assert!(result.ok, "{:?}", result.diagnostics);
        assert!(result.diagnostics.is_empty());
        assert!(result.r_code.contains("42L"), "{}", result.r_code);
        assert!(result.r_code.contains("# === TypR Standard Library ==="));
    }

    #[test]
    fn build_still_returns_r_code_on_type_error() {
        let result = build_source("let x: int <- \"oops\";");
        assert!(!result.ok);
        assert_eq!(result.diagnostics.len(), 1);
        assert!(!result.r_code.is_empty());
    }

    #[test]
    fn build_returns_empty_r_code_on_syntax_error() {
        let result = build_source("let a <- 5");
        assert!(!result.ok);
        assert_eq!(result.diagnostics.len(), 1);
        assert!(result.r_code.is_empty());
    }

    #[test]
    fn syntax_resources_lists_all_seven_resources() {
        let uris: Vec<String> = syntax_resources().into_iter().map(|r| r.uri).collect();
        assert_eq!(
            uris,
            vec![
                LEXICON_URI,
                OPERATORS_URI,
                STDLIB_URI,
                PITFALLS_URI,
                ESCAPE_HATCHES_URI,
                CHEATSHEET_URI,
                DOCS_INDEX_URI,
            ]
        );
    }

    #[test]
    fn read_syntax_resource_returns_the_lexicon_table() {
        let result = read_syntax_resource(LEXICON_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("Kind sigils"), "{text}");
        assert!(text.contains("`#N` | Number | `#`"), "{text}");
    }

    #[test]
    fn read_syntax_resource_returns_the_operators_table() {
        let result = read_syntax_resource(OPERATORS_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("Precedence"), "{text}");
    }

    #[test]
    fn read_syntax_resource_returns_the_stdlib_digest() {
        let result = read_syntax_resource(STDLIB_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("Standard Library"), "{text}");
    }

    #[test]
    fn read_syntax_resource_returns_the_pitfalls_page() {
        let result = read_syntax_resource(PITFALLS_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("Known Pitfalls"), "{text}");
    }

    #[test]
    fn read_syntax_resource_returns_the_escape_hatches_page() {
        let result = read_syntax_resource(ESCAPE_HATCHES_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("Escape Hatches"), "{text}");
    }

    #[test]
    fn read_syntax_resource_returns_the_cheatsheet_page() {
        let result = read_syntax_resource(CHEATSHEET_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("TypR"), "{text}");
    }

    #[test]
    fn read_syntax_resource_returns_the_docs_index() {
        let result = read_syntax_resource(DOCS_INDEX_URI).unwrap();
        let ResourceContents::TextResourceContents { text, .. } = &result.contents[0] else {
            panic!("expected text contents");
        };
        assert!(text.contains("Documentation Index"), "{text}");
    }

    #[test]
    fn parse_docs_index_skips_header_and_separator_rows() {
        let pages = parse_docs_index();
        assert!(pages.len() > 30, "expected ~39 pages, got {}", pages.len());
        assert!(pages.iter().all(|p| !p.title.is_empty() && !p.url.is_empty()));
        assert!(pages.iter().all(|p| p.title != "Title" && p.title != "---"));
    }

    #[test]
    fn parse_docs_index_every_url_is_a_docs_site_link() {
        for page in parse_docs_index() {
            assert!(
                page.url
                    .starts_with("https://we-data-ch.github.io/typr.github.io/docs/"),
                "{}: {}",
                page.title,
                page.url
            );
        }
    }

    #[test]
    fn docs_search_finds_the_dplyr_howto_by_keyword() {
        let result = search_docs("dplyr");
        assert!(!result.matches.is_empty());
        assert!(
            result.matches[0].url.contains("use-dplyr-tidyr"),
            "{:?}",
            result.matches
        );
    }

    #[test]
    fn docs_search_is_case_insensitive() {
        let result = search_docs("DPLYR");
        assert!(!result.matches.is_empty());
    }

    #[test]
    fn docs_search_ranks_title_matches_above_description_only_matches() {
        // "Interfaces & Structural Validation" matches in the title; several
        // other pages only mention "interface" in passing in their description.
        let result = search_docs("interfaces");
        assert!(!result.matches.is_empty());
        assert_eq!(result.matches[0].title, "Interfaces & Structural Validation");
    }

    #[test]
    fn docs_search_caps_results_at_eight() {
        // A single common word ("the" doesn't appear in titles/descriptions by
        // design, so use one that's broad but real: "type" shows up across
        // most of the reference and philosophy sections).
        let result = search_docs("type");
        assert!(result.matches.len() <= 8, "{:?}", result.matches);
    }

    #[test]
    fn docs_search_returns_no_matches_for_a_nonsense_query() {
        let result = search_docs("xyzzy_not_a_real_word_plugh");
        assert!(result.matches.is_empty());
    }

    #[test]
    fn read_syntax_resource_rejects_unknown_uri() {
        assert!(read_syntax_resource("typr://nope").is_err());
    }

    /// Every curated `explain` entry's `bad` example must reproduce exactly
    /// the code it's filed under, and `good` must type-check cleanly — an
    /// entry that drifts from the real compiler is worse than no entry.
    #[test]
    fn explain_entries_are_verified_against_the_compiler() {
        for entry in explain::ENTRIES {
            let bad = check_source(entry.bad);
            assert!(
                !bad.ok,
                "{}: `bad` example unexpectedly type-checks:\n{}",
                entry.code, entry.bad
            );
            assert!(
                bad.diagnostics.iter().any(|d| d.code == entry.code),
                "{}: `bad` example produced {:?}, expected a {} diagnostic:\n{}",
                entry.code,
                bad.diagnostics,
                entry.code,
                entry.bad
            );

            let good = check_source(entry.good);
            assert!(
                good.ok,
                "{}: `good` example doesn't type-check: {:?}\n{}",
                entry.code, good.diagnostics, entry.good
            );
        }
    }

    #[test]
    fn explain_known_code_returns_the_curated_entry() {
        let result = explain_code("T001");
        assert!(result.found);
        assert_eq!(result.code, "T001");
        assert!(result.bad_example.is_some());
        assert!(result.good_example.is_some());
    }

    #[test]
    fn explain_is_case_insensitive() {
        assert!(explain_code("t001").found);
    }

    #[test]
    fn explain_unknown_code_reports_not_found() {
        let result = explain_code("T999");
        assert!(!result.found);
        assert!(result.explanation.is_none());
    }

    #[test]
    fn malformed_function_signature_is_reported_not_panicked() {
        let result = check_source("let f <- fn(a): int { a };");
        assert!(!result.ok);
        assert!(!result.diagnostics.is_empty());
    }

    /// `fn(...)` with neither `:` nor `->` before the body panics deep in the
    /// parser (`elements.rs`) with a raw string, not a `SyntaxError` — the
    /// S000 fallback in `panic_payload_diagnostic` is what stands between
    /// that and a crashed MCP server.
    #[test]
    fn panicking_parse_path_is_caught_not_propagated() {
        let previous_hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));
        let result = check_source("let f <- fn(a: int) { a };");
        std::panic::set_hook(previous_hook);

        assert!(!result.ok);
        assert_eq!(result.diagnostics.len(), 1);
        assert_eq!(result.diagnostics[0].code, "S000");
    }
}

/// Run the MCP server over stdio until the client disconnects.
///
/// Type checking recurses over the AST, so callers should drive this future
/// from a thread with a large stack (the `typr lsp` subcommand sets up an
/// 8MB-stack tokio runtime for the same reason).
pub async fn run_stdio() -> anyhow::Result<()> {
    let service = TyprMcpServer::new().serve(stdio()).await?;
    service.waiting().await?;
    Ok(())
}
