#' @include generic_functions.R
as.Function1 <- function(x) x |> struct(c('Function1', 'Any'))
as.Function0 <- function(x) x |> struct(c('Function0', 'Any'))
as.Foreign0 <- function(x) x |> struct(c('Foreign0', 'Any'))
as.LmModel <- function(x) x |> struct(c('LmModel', 'Foreign0', 'Foreign0', 'Any'))
as.Foreign <- function(x) x |> struct(c('Foreign', 'Any', 'None'))
as.Function65 <- function(x) x |> struct(c('Function65', 'Any'))
as.State0 <- function(x) x |> struct(c('State0', 'Any'))
as.State <- function(x) x |> struct(c('State', 'Any', 'None'))
as.Function60 <- function(x) x |> struct(c('Function60', 'Any'))
as.Function59 <- function(x) x |> struct(c('Function59', 'Any'))
as.Factor0 <- function(x) x |> struct(c('Factor0', 'Any'))
as.Factor <- function(x) x |> struct(c('Factor', 'integer', 'Any'))
as.Array4 <- function(x) x |> struct(c('Array4', 'Any'))
as.Function47 <- function(x) x |> struct(c('Function47', 'Any'))
as.Union0 <- function(x) x |> struct(c('Union0', 'Any'))
as.Function42 <- function(x) x |> struct(c('Function42', 'Any'))
as.Function41 <- function(x) x |> struct(c('Function41', 'Any'))
as.Function38 <- function(x) x |> struct(c('Function38', 'Any'))
as.Function37 <- function(x) x |> struct(c('Function37', 'Any'))
as.Function36 <- function(x) x |> struct(c('Function36', 'Any'))
as.Array3 <- function(x) x |> struct(c('Array3', 'Any'))
as.Iterable <- function(x) x |> struct(c('Iterable', 'Any'))
as.Function26 <- function(x) x |> struct(c('Function26', 'Any'))
as.Function25 <- function(x) x |> struct(c('Function25', 'Any'))
as.Function24 <- function(x) x |> struct(c('Function24', 'Any'))
as.Tag0 <- function(x) x |> struct(c('Tag0', 'Any'))
as.Function21 <- function(x) x |> struct(c('Function21', 'Any'))
as.Function20 <- function(x) x |> struct(c('Function20', 'Any'))
as.Function19 <- function(x) x |> struct(c('Function19', 'Any'))
as.Function18 <- function(x) x |> struct(c('Function18', 'Any'))
as.Function17 <- function(x) x |> struct(c('Function17', 'Any'))
as.Function16 <- function(x) x |> struct(c('Function16', 'Any'))
as.Function14 <- function(x) x |> struct(c('Function14', 'Any'))
as.Function12 <- function(x) x |> struct(c('Function12', 'Any'))
as.Function11 <- function(x) x |> struct(c('Function11', 'Any'))
as.Function5 <- function(x) x |> struct(c('Function5', 'Function0', 'Any'))
as.Empty0 <- function(x) x |> struct(c('Empty0', 'character', 'character', 'integer', 'Foreign0', 'Function0', 'Function1', 'Any'))
as.Function4 <- function(x) x |> struct(c('Function4', 'Any'))
as.Function2 <- function(x) x |> struct(c('Function2', 'Any'))
as.Function1 <- function(x) x |> struct(c('Function1', 'Any'))
as.Function0 <- function(x) x |> struct(c('Function0', 'Any'))
as.Integer <- function(x) x |> struct(c('Integer', 'integer', 'Any'))
as.Character <- function(x) x |> struct(c('Character', 'character', 'Any'))
as.Number <- function(x) x |> struct(c('Number', 'numeric', 'Any'))
as.Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Any'))