Function29 <- function(x) x |> struct(c('Function29', 'Any'))
Function28 <- function(x) x |> struct(c('Function28', 'Any'))
System2 <- function(x) x |> struct(c('System2', 'Any'))
Function27 <- function(x) x |> struct(c('Function27', 'Any'))
Function26 <- function(x) x |> struct(c('Function26', 'Any'))
Array7 <- function(x) x |> struct(c('Array7', 'Any'))
Function25 <- function(x) x |> struct(c('Function25', 'Any'))
Array6 <- function(x) x |> struct(c('Array6', 'Any'))
Function24 <- function(x) x |> struct(c('Function24', 'Any'))
Array5 <- function(x) x |> struct(c('Array5', 'Any'))
Function23 <- function(x) x |> struct(c('Function23', 'Any'))
Array4 <- function(x) x |> struct(c('Array4', 'Any'))
Plot <- function(x) x |> struct(c('Plot', 'Any'))
Function22 <- function(x) x |> struct(c('Function22', 'Any'))
Tag0 <- function(x) x |> struct(c('Tag0', 'Any'))
Array3 <- function(x) x |> struct(c('Array3', 'Any'))
Array2 <- function(x) x |> struct(c('Array2', 'Any'))
Function21 <- function(x) x |> struct(c('Function21', 'Any'))
Function20 <- function(x) x |> struct(c('Function20', 'Any'))
Function19 <- function(x) x |> struct(c('Function19', 'Any'))
Function18 <- function(x) x |> struct(c('Function18', 'Any'))
Option <- function(x) x |> struct(c('Option', 'Any'))
Function17 <- function(x) x |> struct(c('Function17', 'Any'))
Function16 <- function(x) x |> struct(c('Function16', 'Any'))
Function15 <- function(x) x |> struct(c('Function15', 'Any'))
Array1 <- function(x) x |> struct(c('Array1', 'Any'))
Function14 <- function(x) x |> struct(c('Function14', 'Any'))
Function13 <- function(x) x |> struct(c('Function13', 'Any'))
Function12 <- function(x) x |> struct(c('Function12', 'Any'))
Function11 <- function(x) x |> struct(c('Function11', 'Any'))
Function10 <- function(x) x |> struct(c('Function10', 'Any'))
Function9 <- function(x) x |> struct(c('Function9', 'Any'))
Function8 <- function(x) x |> struct(c('Function8', 'Any'))
Function7 <- function(x) x |> struct(c('Function7', 'Any'))
Function6 <- function(x) x |> struct(c('Function6', 'Any'))
Function5 <- function(x) x |> struct(c('Function5', 'Any'))
Empty0 <- function(x) x |> struct(c('Empty0', 'Any'))
Function4 <- function(x) x |> struct(c('Function4', 'Any'))
Function3 <- function(x) x |> struct(c('Function3', 'Any'))
Array0 <- function(x) x |> struct(c('Array0', 'Any'))
Function2 <- function(x) x |> struct(c('Function2', 'Any'))
Function1 <- function(x) x |> struct(c('Function1', 'Any'))
Function0 <- function(x) x |> struct(c('Function0', 'Any'))
Generic <- function(x) x |> struct(c('Generic', 'Any'))
Integer <- function(x) x |> struct(c('Integer', 'integer', 'Any'))
Character <- function(x) x |> struct(c('Character', 'character', 'Any'))
Number <- function(x) x |> struct(c('Number', 'numeric', 'Any'))
Boolean <- function(x) x |> struct(c('Boolean', 'logical', 'Any'))