[[rule]]
file = "@run"
must_contain = "successful"

[[rule]]
file = "@run"
must_not_contain = "Type errors found"

[[rule]]
file = "@run"
must_not_contain = "doesn't match type"

[[rule]]
file = "R/main.R"
must_contain = "my_addition(num1, num2)"
