//! Reproducible bug catalog for TypR (`typr case …`).
//!
//! Each case is a self-contained folder under `cases/`:
//!
//! ```text
//! cases/0001-mon-bug/
//!   case.toml      # cmd (build|check|debug|run), layer, status, title, created, origin
//!   repro/         # a REAL TypR project (TypR/main.ty, …) replayed by `typr <cmd>`
//!   expect.toml    # ORACLE: must_contain / must_not_contain rules grep'd on the generated R
//!                  # (or, for file = "@run", on the captured stdout+stderr of a real R run)
//!   expect.md      # what SHOULD happen (prose) + code localization
//!   observed.txt   # the broken R / error at report time
//!   golden/        # (fixed cases) captured target R/*.R → regression diff (never "@run": noisy)
//! ```
//!
//! Phase 1 does NOT execute R: `typr build` writes `R/*.R` before the `document()` step, so the
//! grep oracle works even when `document()` fails (R/devtools absent). `golden/` is captured by
//! `freeze`, never written by hand.
//!
//! Phase 2 (`layer = "r-run"`) DOES execute R: pair it with `cmd = "run"`, which runs
//! `typr run` — build + `Rscript` execution of the project's actual entry point — in the
//! sandbox. Rules with `file = "@run"` then grep the captured stdout+stderr of that real R
//! process instead of a generated file, e.g. `must_not_contain = "no applicable method"`. This
//! is the only way to catch bugs that are invisible in the generated R text but blow up at
//! runtime (wrong S3 dispatch, wrong argument order, …). Fails open: if `Rscript` isn't on
//! PATH, the underlying `typr run` fails and every `@run` rule fails too — same as any other
//! missing dependency, no special-casing needed here. `@run` is never golden-diffed
//! (`ruled_files` excludes it): the captured text includes CLI progress timings
//! (`done (N ms)`), which differ every run — golden stays for deterministic `R/*.R` text only.

#![allow(dead_code)]

use serde::Deserialize;
use serde::Serialize;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

const CASES_DIR: &str = "cases";

const GREEN: &str = "\x1b[32m";
const CYAN: &str = "\x1b[36m";
const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const GREY: &str = "\x1b[90m";
const BOLD: &str = "\x1b[1m";
const RESET: &str = "\x1b[0m";

const EXPECT_SKELETON: &str = "# Règles oracle (grep). Décommente et adapte :\n\
    #[[rule]]\n#file = \"R/main.R\"\n#must_contain = \"motif attendu\"\n\
    #[[rule]]\n#file = \"R/main.R\"\n#must_not_contain = \"motif interdit\"\n\
    # Cas layer=\"r-run\" (cmd=\"run\") : file = \"@run\" grep le stdout+stderr de\n\
    # l'exécution R réelle plutôt qu'un fichier généré, ex. :\n\
    #[[rule]]\n#file = \"@run\"\n#must_not_contain = \"no applicable method\"\n\
    #[[rule]]\n#file = \"@run\"\n#must_contain = \"42\"\n";

pub const MINIMAL_DESCRIPTION: &str =
    "Package: repro\nTitle: TypR repro case\nVersion: 0.0.0.9000\n\
    Description: Minimal reproduction project for `typr case`.\nEncoding: UTF-8\n";

pub const MINIMAL_NAMESPACE: &str = "# Generated by roxygen2: do not edit by hand\n";

const LOCALISATION_HDR: &str = "## Localisation (#@case)\n\n";

/// A `#@case [slug:] description` marker found in the project's TypR sources.
struct Marker {
    file: String,
    line: usize,
    slug: Option<String>,
    desc: String,
}

#[derive(Debug, Default, Deserialize, Serialize)]
struct CaseMeta {
    #[serde(default)]
    title: String,
    #[serde(default = "default_cmd")]
    cmd: String,
    #[serde(default)]
    layer: String,
    #[serde(default = "default_status")]
    status: String,
    #[serde(default)]
    created: String,
    #[serde(default)]
    origin: String,
    /// Replay this case's `cmd` (`build`/`run` only) with `--checked`
    /// (soundness_transpilation.md Phase A/D): lets an interop-matrix case
    /// double as a `typr_assert_type` oracle run without a separate harness.
    #[serde(default)]
    checked: bool,
}

fn default_cmd() -> String {
    "build".to_string()
}

fn default_status() -> String {
    "open".to_string()
}

#[derive(Debug, Default, Deserialize)]
struct ExpectFile {
    #[serde(default)]
    rule: Vec<Rule>,
}

#[derive(Debug, Deserialize)]
struct Rule {
    file: String,
    must_contain: Option<String>,
    must_not_contain: Option<String>,
}

struct Sandbox {
    work: PathBuf,
    exit: i32,
    stdout: String,
    stderr: String,
}

struct RuleResult {
    ok: bool,
    msg: String,
}

// ── helpers ─────────────────────────────────────────────────────────────────

fn case_dirs() -> Vec<PathBuf> {
    let dir = PathBuf::from(CASES_DIR);
    if !dir.exists() {
        return vec![];
    }
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(&dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.is_dir())
                .collect()
        })
        .unwrap_or_default();
    dirs.sort();
    dirs
}

fn basename(p: &Path) -> String {
    p.file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("")
        .to_string()
}

fn pad4(s: &str) -> String {
    if s.len() >= 4 {
        s.to_string()
    } else {
        format!("{:0>4}", s)
    }
}

/// Resolve an id/slug ("1", "0001", "module") to a single case path.
fn resolve_case(id: &str) -> PathBuf {
    let padded = pad4(id);
    let hits: Vec<PathBuf> = case_dirs()
        .into_iter()
        .filter(|d| {
            let b = basename(d);
            b.starts_with(&padded) || b.contains(id)
        })
        .collect();
    if hits.is_empty() {
        eprintln!("{RED}Aucun cas ne correspond à '{id}'{RESET}");
        std::process::exit(1);
    }
    if hits.len() > 1 {
        eprintln!("{YELLOW}Plusieurs cas correspondent à '{id}':{RESET}");
        for h in &hits {
            eprintln!("  {}", h.display());
        }
        std::process::exit(1);
    }
    hits.into_iter().next().unwrap()
}

fn read_meta(case: &Path) -> CaseMeta {
    let path = case.join("case.toml");
    match std::fs::read_to_string(&path) {
        Ok(s) => toml::from_str(&s).unwrap_or_default(),
        Err(_) => CaseMeta::default(),
    }
}

pub fn copy_dir(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let path = entry.path();
        let target = dst.join(entry.file_name());
        if path.is_dir() {
            copy_dir(&path, &target)?;
        } else {
            std::fs::copy(&path, &target)?;
        }
    }
    Ok(())
}

pub fn unique_tmp() -> PathBuf {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    std::env::temp_dir().join(format!("typr-case-{}-{}", std::process::id(), nanos))
}

/// Copy `repro/` into a temp sandbox and run `typr <cmd>` (this same binary) inside it.
fn build_sandbox(case: &Path) -> Sandbox {
    let meta = read_meta(case);
    let repro = case.join("repro");
    let tmp = unique_tmp();
    let work = tmp.join("work");
    if let Err(e) = copy_dir(&repro, &work) {
        eprintln!(
            "{RED}Impossible de copier le repro de {}: {e}{RESET}",
            case.display()
        );
        std::process::exit(1);
    }
    let exe = std::env::current_exe().expect("current exe path");
    let mut command = Command::new(exe);
    command.arg(&meta.cmd).current_dir(&work);
    if meta.checked && (meta.cmd == "build" || meta.cmd == "run") {
        command.arg("--checked");
    }
    let output = command.output();
    match output {
        Ok(out) => Sandbox {
            work,
            exit: out.status.code().unwrap_or(-1),
            stdout: String::from_utf8_lossy(&out.stdout).into_owned(),
            stderr: String::from_utf8_lossy(&out.stderr).into_owned(),
        },
        Err(e) => {
            eprintln!("{RED}Échec de l'exécution de typr {}: {e}{RESET}", meta.cmd);
            std::process::exit(1);
        }
    }
}

fn read_expect(case: &Path) -> ExpectFile {
    let path = case.join("expect.toml");
    match std::fs::read_to_string(&path) {
        Ok(s) => toml::from_str(&s).unwrap_or_default(),
        Err(_) => ExpectFile::default(),
    }
}

/// Virtual rule target name for the captured stdout+stderr of an R execution
/// (`cmd = "run"`, `layer = "r-run"`), as opposed to a generated `R/*.R` file.
const RUN_TARGET: &str = "@run";

/// Combined stdout+stderr of the sandbox's `typr <cmd>` invocation — what a
/// `file = "@run"` rule greps, since real R runtime errors (e.g. "no
/// applicable method") never land in a generated `R/*.R` file.
fn run_output_text(sb: &Sandbox) -> String {
    format!("{}\n{}", sb.stdout, sb.stderr)
}

/// Apply the expect.toml rules on the sandboxed run: `R/*.R` files on disk,
/// or (for `file = "@run"`) the captured stdout+stderr of the R execution.
fn check_rules(case: &Path, sb: &Sandbox) -> Vec<RuleResult> {
    read_expect(case)
        .rule
        .iter()
        .map(|r| {
            let content = if r.file == RUN_TARGET {
                run_output_text(sb)
            } else {
                let target = sb.work.join(&r.file);
                if !target.exists() {
                    return RuleResult {
                        ok: false,
                        msg: format!("{} absent (non généré)", r.file),
                    };
                }
                std::fs::read_to_string(&target).unwrap_or_default()
            };
            if let Some(p) = &r.must_contain {
                RuleResult {
                    ok: content.contains(p),
                    msg: format!("{} doit contenir « {} »", r.file, p),
                }
            } else if let Some(p) = &r.must_not_contain {
                RuleResult {
                    ok: !content.contains(p),
                    msg: format!("{} ne doit PAS contenir « {} »", r.file, p),
                }
            } else {
                RuleResult {
                    ok: false,
                    msg: format!(
                        "règle invalide pour {} (ni must_contain ni must_not_contain)",
                        r.file
                    ),
                }
            }
        })
        .collect()
}

/// Unique R files referenced by the rules (targeted golden, no stdlib noise).
///
/// Excludes `@run`: its captured text carries CLI progress chatter with elapsed-ms timings
/// (`progress.rs`'s `Step`), which differ on every invocation. Byte-exact golden diffing on it
/// would false-positive as REGRESS on every run. `@run` stays grep-only, same philosophy as the
/// rest of this oracle ("never hand-written/exact-matched R", just substring rules).
fn ruled_files(case: &Path) -> Vec<String> {
    let mut files: Vec<String> = read_expect(case)
        .rule
        .into_iter()
        .map(|r| r.file)
        .filter(|f| f != RUN_TARGET)
        .collect();
    files.sort();
    files.dedup();
    files
}

fn cleanup(work: &Path, keep: bool) {
    if keep {
        println!("        sandbox: {}", work.display());
    } else if let Some(parent) = work.parent() {
        let _ = std::fs::remove_dir_all(parent);
    }
}

// ── commands ──────────────────────────────────────────────────────────────────

pub fn list(status: Option<String>) {
    let dirs = case_dirs();
    let rows: Vec<(String, String, String, String)> = dirs
        .iter()
        .map(|d| {
            let meta = read_meta(d);
            let id = basename(d).split('-').next().unwrap_or("").to_string();
            (id, meta.status, meta.layer, meta.title)
        })
        .filter(|(_, s, _, _)| status.as_ref().map(|f| f == s).unwrap_or(true))
        .collect();

    if rows.is_empty() {
        println!("Aucun cas.");
        return;
    }
    println!(
        "{BOLD}{:<6} {:<8} {:<10} title{RESET}",
        "id", "status", "layer"
    );
    for (id, s, layer, title) in rows {
        println!("{:<6} {:<8} {:<10} {}", id, s, layer, title);
    }
}

pub fn run(filter: Option<String>, status: Option<String>, keep: bool) {
    let dirs: Vec<PathBuf> = case_dirs()
        .into_iter()
        .filter(|d| {
            filter
                .as_ref()
                .map(|f| basename(d).contains(f.as_str()))
                .unwrap_or(true)
        })
        .filter(|d| {
            status
                .as_ref()
                .map(|f| &read_meta(d).status == f)
                .unwrap_or(true)
        })
        .collect();

    if dirs.is_empty() {
        println!("Aucun cas à rejouer.");
        return;
    }

    let mut any_regress = false;
    let mut counts: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();

    for case in &dirs {
        let meta = read_meta(case);
        let sb = build_sandbox(case);
        let checks = check_rules(case, &sb);
        let failed: Vec<&RuleResult> = checks.iter().filter(|c| !c.ok).collect();
        let rules_pass = !checks.is_empty() && failed.is_empty();

        // targeted golden diff (fixed cases only)
        let golden = case.join("golden");
        let mut golden_mismatch: Vec<String> = vec![];
        if golden.exists() {
            for rel in ruled_files(case) {
                let g = golden.join(&rel);
                let w = sb.work.join(&rel);
                let same = match (std::fs::read_to_string(&g), std::fs::read_to_string(&w)) {
                    (Ok(a), Ok(b)) => a == b,
                    _ => false,
                };
                if !same {
                    golden_mismatch.push(rel);
                }
            }
        }
        let golden_ok = golden_mismatch.is_empty();

        let verdict = match meta.status.as_str() {
            "fixed" => {
                if rules_pass && golden_ok {
                    "PASS"
                } else {
                    "REGRESS"
                }
            }
            "wontfix" => "SKIP",
            _ => {
                if rules_pass {
                    "READY"
                } else {
                    "OPEN"
                }
            }
        };
        if verdict == "REGRESS" {
            any_regress = true;
        }

        let color = match verdict {
            "PASS" => GREEN,
            "READY" => CYAN,
            "REGRESS" => RED,
            "OPEN" => YELLOW,
            _ => GREY,
        };
        println!("{color}[{verdict}]{RESET}  {}", basename(case));
        for c in &failed {
            println!("        ✗ {}", c.msg);
        }
        for d in &golden_mismatch {
            println!("        ✗ golden diff: {d}");
        }

        cleanup(&sb.work, keep);
        *counts.entry(verdict.to_string()).or_insert(0) += 1;
    }

    let summary = counts
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect::<Vec<_>>()
        .join("  ");
    println!("\nRésumé : {summary}");
    if any_regress {
        println!("{RED}Régression détectée.{RESET}");
        std::process::exit(1);
    }
}

pub fn add(slug: &str, from: Option<String>, cmd: &str, layer: &str) {
    let cases = PathBuf::from(CASES_DIR);
    if !cases.exists() {
        let _ = std::fs::create_dir_all(&cases);
    }
    let n = case_dirs().len() + 1;
    let id = format!("{:04}", n);
    let dir = cases.join(format!("{id}-{slug}"));
    if let Err(e) = std::fs::create_dir_all(&dir) {
        eprintln!("{RED}Impossible de créer {}: {e}{RESET}", dir.display());
        std::process::exit(1);
    }

    match from {
        // Curated copy (TypR/ + DESCRIPTION/NAMESPACE only), same as `snapshot` — avoids
        // dragging renv/.git/large caches from a real project into the catalog.
        Some(src) => {
            if let Err(e) = copy_repro_curated(&PathBuf::from(&src), &dir.join("repro")) {
                eprintln!("{RED}Impossible de copier {src}: {e}{RESET}");
                std::process::exit(1);
            }
        }
        None => {
            let _ = std::fs::create_dir_all(dir.join("repro/TypR"));
            let _ = std::fs::create_dir_all(dir.join("repro/R"));
            let _ = std::fs::write(dir.join("repro/TypR/main.ty"), "mod main;\n");
        }
    }

    let today = current_date();
    let meta = CaseMeta {
        title: format!("TODO: décrire {slug}"),
        cmd: cmd.to_string(),
        layer: layer.to_string(),
        status: "open".to_string(),
        created: today,
        origin: "perso".to_string(),
        checked: false,
    };
    let _ = std::fs::write(
        dir.join("case.toml"),
        toml::to_string(&meta).unwrap_or_default(),
    );

    let _ = std::fs::write(dir.join("expect.toml"), EXPECT_SKELETON);
    let _ = std::fs::write(
        dir.join("expect.md"),
        format!("# {slug}\n\n## Ce qui DEVRAIT se passer\n\nTODO\n"),
    );

    // capture observed.txt
    let sb = build_sandbox(&dir);
    let r_dump = dump_generated_r(&sb.work);
    let _ = std::fs::write(
        dir.join("observed.txt"),
        format!(
            "# exit={}\n\n## stdout/stderr\n{}\n{}\n\n## R généré\n{}\n",
            sb.exit, sb.stdout, sb.stderr, r_dump
        ),
    );
    cleanup(&sb.work, false);

    println!("Cas créé : {}", dir.display());
    println!("  → édite case.toml (title, layer), expect.toml (règles), expect.md.");
}

pub fn freeze(id: &str) {
    let case = resolve_case(id);
    let sb = build_sandbox(&case);

    let mut files = ruled_files(&case);
    if files.is_empty() {
        // no rules: freeze every generated R file
        files = list_generated_r(&sb.work);
    }

    let golden = case.join("golden");
    let _ = std::fs::remove_dir_all(&golden);
    for rel in &files {
        let src = sb.work.join(rel);
        let dst = golden.join(rel);
        if let Some(parent) = dst.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if let Err(e) = std::fs::copy(&src, &dst) {
            eprintln!("{YELLOW}Avertissement: golden {rel} non figé: {e}{RESET}");
        }
    }
    cleanup(&sb.work, false);

    let mut meta = read_meta(&case);
    meta.status = "fixed".to_string();
    let _ = std::fs::write(
        case.join("case.toml"),
        toml::to_string(&meta).unwrap_or_default(),
    );

    println!("Golden figé pour {} :", basename(&case));
    for f in &files {
        println!("  {f}");
    }
    println!("status → fixed");
}

pub fn show(id: &str) {
    let case = resolve_case(id);
    println!("{GREEN}{BOLD}{}{RESET}\n", basename(&case));
    println!("── case.toml ──");
    if let Ok(s) = std::fs::read_to_string(case.join("case.toml")) {
        print!("{s}");
    }
    let ep = case.join("expect.md");
    if let Ok(s) = std::fs::read_to_string(&ep) {
        println!("\n── expect.md ──");
        print!("{s}");
    }
    let rp = case.join("expect.toml");
    if let Ok(s) = std::fs::read_to_string(&rp) {
        println!("\n── expect.toml (règles) ──");
        print!("{s}");
    }
}

/// Snapshot the current TypR project into a self-contained case bundle, *inside the project*.
/// The user then moves `<slug>.case/` into the `cases/` catalog of the typr repo themselves.
/// Description comes from `//@case` markers in the TypR sources and/or a `.case.md` note
/// (created here as a skeleton if absent).
pub fn snapshot(slug_arg: Option<String>) {
    let project = PathBuf::from(".");
    if !project.join("TypR/main.ty").exists() {
        eprintln!(
            "{RED}Pas de TypR/main.ty ici : lance `typr case snapshot` depuis la racine d'un projet TypR.{RESET}"
        );
        std::process::exit(1);
    }

    let markers = scan_markers(&project);

    // Ensure a .case.md note exists (create a skeleton from the markers if absent).
    let case_md_path = project.join(".case.md");
    let created_case_md = !case_md_path.exists();
    if created_case_md {
        let _ = std::fs::write(&case_md_path, build_case_md_skeleton(&markers));
    }
    let case_md = std::fs::read_to_string(&case_md_path).unwrap_or_default();

    // Resolve slug: CLI arg > first marker slug > .case.md heading > project dir name.
    let slug = slug_arg
        .filter(|s| !s.is_empty())
        .or_else(|| markers.iter().find_map(|m| m.slug.clone()))
        .or_else(|| first_heading(&case_md).map(|h| slugify(&h)))
        .filter(|s| !s.is_empty())
        .or_else(|| {
            std::env::current_dir()
                .ok()
                .and_then(|d| d.file_name().map(|s| slugify(&s.to_string_lossy())))
        })
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "snapshot".to_string());

    let title = first_heading(&case_md)
        .or_else(|| {
            markers
                .iter()
                .map(|m| m.desc.clone())
                .find(|d| !d.is_empty())
        })
        .unwrap_or_else(|| slug.clone());

    // Build the bundle (refresh if it already exists).
    let bundle = project.join(format!("{slug}.case"));
    let _ = std::fs::remove_dir_all(&bundle);
    if let Err(e) = std::fs::create_dir_all(&bundle) {
        eprintln!("{RED}Impossible de créer {}: {e}{RESET}", bundle.display());
        std::process::exit(1);
    }
    let repro = bundle.join("repro");
    if let Err(e) = copy_repro_curated(&project, &repro) {
        eprintln!("{RED}Échec du snapshot des sources: {e}{RESET}");
        std::process::exit(1);
    }

    let meta = CaseMeta {
        title,
        cmd: "build".to_string(),
        layer: "transpile".to_string(),
        status: "open".to_string(),
        created: current_date(),
        origin: "perso".to_string(),
        checked: false,
    };
    let _ = std::fs::write(
        bundle.join("case.toml"),
        toml::to_string(&meta).unwrap_or_default(),
    );

    // expect.md = the .case.md note (which, when freshly created, already lists the markers).
    // Only append the localization block if the note doesn't already carry one.
    let mut expect_md = case_md.clone();
    if !markers.is_empty() && !expect_md.contains("## Localisation") {
        expect_md.push('\n');
        expect_md.push_str(LOCALISATION_HDR);
        for m in &markers {
            expect_md.push_str(&marker_line(m));
        }
    }
    let _ = std::fs::write(bundle.join("expect.md"), expect_md);
    let _ = std::fs::write(bundle.join("expect.toml"), EXPECT_SKELETON);

    // observed.txt = a captured build of the snapshot.
    let _ = std::fs::write(bundle.join("observed.txt"), capture_observed(&repro));

    println!("{GREEN}Snapshot créé : {}{RESET}", bundle.display());
    if created_case_md {
        println!(
            "  .case.md créé à la racine — complète-le, puis relance pour rafraîchir le bundle."
        );
    }
    if markers.is_empty() {
        println!(
            "  (aucun marqueur #@case ; ajoute `#@case slug: description` près du code fautif)"
        );
    } else {
        println!("  {} marqueur(s) #@case capturé(s).", markers.len());
    }
    println!(
        "  → déplace `{}` dans <repo-typr>/cases/ (en NNNN-{slug}), puis édite expect.toml (anomalies → règles).",
        bundle.display()
    );
}

/// Scan `TypR/**/*.ty` for `//@case [slug:] description` markers.
fn scan_markers(project: &Path) -> Vec<Marker> {
    let mut out = vec![];
    let mut stack = vec![project.join("TypR")];
    while let Some(dir) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in rd.filter_map(|e| e.ok()) {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
                continue;
            }
            if p.extension().and_then(|s| s.to_str()) != Some("ty") {
                continue;
            }
            let Ok(content) = std::fs::read_to_string(&p) else {
                continue;
            };
            for (i, line) in content.lines().enumerate() {
                // A marker is `@case …` inside a TypR comment, i.e. preceded by `#`
                // (`#@case`, `# @case`, leading indentation allowed).
                if let Some(pos) = line.find("@case") {
                    if !line[..pos].trim_end().ends_with('#') {
                        continue;
                    }
                    let (slug, desc) = parse_marker(line[pos + "@case".len()..].trim());
                    let rel = p
                        .strip_prefix(project)
                        .unwrap_or(&p)
                        .to_string_lossy()
                        .into_owned();
                    out.push(Marker {
                        file: rel,
                        line: i + 1,
                        slug,
                        desc,
                    });
                }
            }
        }
    }
    out.sort_by(|a, b| (&a.file, a.line).cmp(&(&b.file, b.line)));
    out
}

/// Split a marker payload into an optional leading single-token slug and the description.
fn parse_marker(rest: &str) -> (Option<String>, String) {
    if let Some((left, right)) = rest.split_once(':') {
        let left = left.trim();
        if !left.is_empty() && !left.contains(char::is_whitespace) {
            return (Some(left.to_string()), right.trim().to_string());
        }
    }
    (None, rest.to_string())
}

fn marker_line(m: &Marker) -> String {
    if m.desc.is_empty() {
        format!("- `{}:{}`\n", m.file, m.line)
    } else {
        format!("- `{}:{}` — {}\n", m.file, m.line, m.desc)
    }
}

fn build_case_md_skeleton(markers: &[Marker]) -> String {
    let title = markers
        .iter()
        .map(|m| m.desc.clone())
        .find(|d| !d.is_empty())
        .unwrap_or_else(|| "TODO: titre du bug".to_string());
    let mut s = format!(
        "# {title}\n\n## Ce qui devrait se passer\n\nTODO\n\n\
         ## Anomalies (→ règles expect.toml)\n\n- TODO: ce qui est faux dans le R généré\n"
    );
    if !markers.is_empty() {
        s.push('\n');
        s.push_str(LOCALISATION_HDR);
        for m in markers {
            s.push_str(&marker_line(m));
        }
    }
    s
}

/// Copy only the package-relevant files (TypR/ + DESCRIPTION/NAMESPACE) into a fresh repro/.
fn copy_repro_curated(project: &Path, repro: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(repro)?;
    let typr_src = project.join("TypR");
    if typr_src.is_dir() {
        copy_dir(&typr_src, &repro.join("TypR"))?;
    }
    for f in ["DESCRIPTION", "NAMESPACE"] {
        let src = project.join(f);
        if src.is_file() {
            std::fs::copy(&src, repro.join(f))?;
        }
    }
    if !repro.join("DESCRIPTION").exists() {
        std::fs::write(repro.join("DESCRIPTION"), MINIMAL_DESCRIPTION)?;
    }
    if !repro.join("NAMESPACE").exists() {
        std::fs::write(repro.join("NAMESPACE"), MINIMAL_NAMESPACE)?;
    }
    std::fs::create_dir_all(repro.join("R"))?;
    std::fs::write(repro.join("R/.gitkeep"), "")?;
    Ok(())
}

/// Run `typr build` on a temp copy of `repro` and format the captured output.
fn capture_observed(repro: &Path) -> String {
    let tmp = unique_tmp();
    let work = tmp.join("work");
    if copy_dir(repro, &work).is_err() {
        return String::new();
    }
    let exe = std::env::current_exe().expect("current exe path");
    let result = match Command::new(exe).arg("build").current_dir(&work).output() {
        Ok(o) => format!(
            "# exit={}\n\n## stdout/stderr\n{}\n{}\n\n## R généré\n{}\n",
            o.status.code().unwrap_or(-1),
            String::from_utf8_lossy(&o.stdout),
            String::from_utf8_lossy(&o.stderr),
            dump_generated_r(&work),
        ),
        Err(e) => format!("# build n'a pas pu démarrer: {e}\n"),
    };
    let _ = std::fs::remove_dir_all(&tmp);
    result
}

fn slugify(s: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for c in s.chars() {
        if c.is_alphanumeric() {
            out.extend(c.to_lowercase());
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('-');
            prev_dash = true;
        }
    }
    out.trim_matches('-').to_string()
}

fn first_heading(md: &str) -> Option<String> {
    md.lines()
        .find_map(|l| l.strip_prefix("# ").map(|h| h.trim().to_string()))
}

// ── small utils ────────────────────────────────────────────────────────────────

fn list_generated_r(work: &Path) -> Vec<String> {
    let r_dir = work.join("R");
    let mut out = vec![];
    if let Ok(rd) = std::fs::read_dir(&r_dir) {
        for e in rd.filter_map(|e| e.ok()) {
            let name = e.file_name().to_string_lossy().into_owned();
            if name.ends_with(".R") {
                out.push(format!("R/{name}"));
            }
        }
    }
    out.sort();
    out
}

fn dump_generated_r(work: &Path) -> String {
    list_generated_r(work)
        .iter()
        .map(|rel| {
            let content = std::fs::read_to_string(work.join(rel)).unwrap_or_default();
            format!("=== {rel} ===\n{content}")
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// YYYY-MM-DD without pulling in a date crate.
pub fn current_date() -> String {
    // days since epoch → civil date (Howard Hinnant's algorithm)
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as i64;
    let z = secs / 86_400 + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{:04}-{:02}-{:02}", y, m, d)
}
