//! Phase C of `soundness_transpilation.md` — a static oracle that intersects,
//! at compile time, every top-level name `typr build` is about to emit
//! (`UseMethod` stubs in `generic_functions.R`, record constructors) against
//! a database of the rest of R's object systems (base-R S3/S4 generics,
//! known S4 classes). This catches the "collision with the rest of R" bug
//! family exhaustively and without ever running R — the historical example
//! is the `nlevels` bug documented in CLAUDE.md: `nlevels` is a *plain*
//! base-R function (not S3-generic), so shadowing it with a bare `UseMethod`
//! stub and no `nlevels.default` fallback leaves no method to dispatch to.
//!
//! The database itself (`configs/src/r_name_db.json`) is generated by
//! `tools/gen_r_name_db.R`, run by hand and committed — see that script's
//! header comment for regeneration instructions.

use serde::Deserialize;
use std::collections::HashMap;

const R_NAME_DB_JSON: &str = include_str!("../configs/src/r_name_db.json");
const STD_R: &str = include_str!("../configs/src/std.R");

#[derive(Debug, Deserialize)]
struct RNameEntry {
    #[allow(dead_code)]
    pkg: String,
    s3_generic: bool,
    s4_generic: bool,
    has_default: bool,
}

#[derive(Debug, Deserialize)]
struct RNameDb {
    #[allow(dead_code)]
    r_version: String,
    names: HashMap<String, RNameEntry>,
    s4_classes: Vec<String>,
}

fn load_db() -> RNameDb {
    serde_json::from_str(R_NAME_DB_JSON)
        .expect("configs/src/r_name_db.json is malformed — regenerate via tools/gen_r_name_db.R")
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LintSeverity {
    Error,
    Warning,
}

#[derive(Debug, Clone)]
pub struct LintFinding {
    pub severity: LintSeverity,
    /// Only read by tests/integration callers matching on the offending
    /// name rather than parsing `message` — the binary's own `report_findings`
    /// prints `message` alone, which already interpolates the name.
    #[allow(dead_code)]
    pub name: String,
    pub message: String,
}

impl LintFinding {
    #[allow(dead_code)]
    pub fn is_error(&self) -> bool {
        self.severity == LintSeverity::Error
    }
}

/// Whether `<name>.default` is present anywhere in the R the build is about
/// to emit — either typr's own hand-written fallback in `std.R` (the
/// `max`/`max.default`, `nlevels`/`nlevels.default` pattern) or one written
/// by user/project code (`generated_r`, the transpiled program body).
fn emits_default(name: &str, generated_r: &str) -> bool {
    let needle = format!("{name}.default");
    STD_R.contains(&needle) || generated_r.contains(&needle)
}

/// Stdlib names registered with a **zero-parameter** signature (`() -> T`,
/// e.g. `@dir: () -> [#N, char];` / `@getwd: () -> char;` in `file.ty`) that
/// still get the standard `name <- function(x, ...) UseMethod('name', x)`
/// stub every typed function name receives. Calling them with zero
/// arguments — as their own signature demands — fails on the missing `x`
/// receiver *before* `UseMethod` ever dispatches, regardless of whether a
/// `.default` method exists: adding one cannot fix this. This is a distinct,
/// deeper mismatch between zero-arity stdlib signatures and the generic-stub
/// codegen (`Context::get_all_generic_functions` unconditionally wraps every
/// typed name the same way), not a name collision this lint's fallback
/// mechanism can paper over — tracked separately rather than papered over
/// with a `.default` that would never actually be reached.
const ZERO_ARITY_STDLIB_EXEMPT: &[&str] = &["dir", "getwd"];

/// Lint every name about to be emitted as a bare `name <- function(x, ...)
/// UseMethod('name', x)` stub in `generic_functions.R` (see
/// `Context::get_all_generic_functions`). `strict` escalates the S4-generic
/// warning to an error.
pub fn lint_generic_stub_names(
    names: &[String],
    generated_r: &str,
    strict: bool,
) -> Vec<LintFinding> {
    let db = load_db();
    let mut findings = Vec::new();
    for name in names {
        if ZERO_ARITY_STDLIB_EXEMPT.contains(&name.as_str()) {
            continue;
        }
        let Some(entry) = db.names.get(name) else {
            continue;
        };
        let has_fallback = entry.has_default || emits_default(name, generated_r);

        // Row 1: not dispatch-capable through *either* object system, and no
        // fallback emitted — the exact shape of the historical `nlevels` bug.
        // Checked independently of the S4 row below: a name that IS a known
        // S4 generic gets only the S4 warning (row 2), since that warning's
        // message already covers the missing-fallback risk for that case.
        if !entry.s3_generic && !entry.s4_generic && !has_fallback {
            findings.push(LintFinding {
                severity: LintSeverity::Error,
                name: name.clone(),
                message: format!(
                    "`{name}` shadows a base-R function that is not S3-generic, and no \
                     `{name}.default` fallback is emitted. This is the historical `nlevels` bug: \
                     any call to `{name}` in the generated R will fail at runtime with \
                     \"no applicable method for '{name}'\". Add a `{name}.default` implementation \
                     to configs/src/std.R (see the `max`/`nlevels` pattern in CLAUDE.md), or rename \
                     the TypR function so it stops colliding."
                ),
            });
            continue;
        }

        // Row 2: known S4 generic — the UseMethod stub masks S4 dispatch for
        // any package attached later, regardless of whether an S3 fallback
        // exists (S4 objects don't dispatch through S3 `.default` anyway).
        if entry.s4_generic {
            let fallback_note = if has_fallback {
                String::new()
            } else {
                format!(
                    " No `{name}.default` fallback is emitted either, so any S3-style call to \
                     `{name}` on a non-matching object will also fail at runtime."
                )
            };
            findings.push(LintFinding {
                severity: if strict {
                    LintSeverity::Error
                } else {
                    LintSeverity::Warning
                },
                name: name.clone(),
                message: format!(
                    "`{name}` is a known S4 generic (package `methods`). The `UseMethod` stub \
                     emitted for it shadows S4 dispatch for `{name}` in any package attached later \
                     in the same R session.{fallback_note}"
                ),
            });
        }
    }
    findings
}

/// Lint record-constructor names (`type X <- list { ... }` targets) against
/// known built-in S4 class names.
pub fn lint_record_constructor_names(names: &[String]) -> Vec<LintFinding> {
    let db = load_db();
    names
        .iter()
        .filter(|name| db.s4_classes.iter().any(|c| c == *name))
        .map(|name| LintFinding {
            severity: LintSeverity::Warning,
            name: name.clone(),
            message: format!(
                "record constructor `{name}` has the same name as a built-in S4 class. The \
                 generated `structure(list(...), class = c(\"{name}\", \"list\"))` value is \
                 unrelated to that S4 class, which may confuse code that inspects classes \
                 structurally (e.g. `is(x, \"{name}\")`)."
            ),
        })
        .collect()
}

/// Print findings to stderr the same way syntax/type errors are reported —
/// errors in red, warnings plain. Returns whether any error-level finding
/// was present (callers use this to decide whether to abort the build).
pub fn report_findings(findings: &[LintFinding]) -> bool {
    let mut has_error = false;
    for finding in findings {
        match finding.severity {
            LintSeverity::Error => {
                has_error = true;
                eprintln!("\x1b[31merror[r-name-lint]\x1b[0m: {}", finding.message);
            }
            LintSeverity::Warning => {
                eprintln!("\x1b[33mwarning[r-name-lint]\x1b[0m: {}", finding.message);
            }
        }
    }
    has_error
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_base_collision_is_an_error_without_any_default() {
        // `crossprod` is plain (non-generic) base R and typr never touches
        // it at all — this is exactly the shape of the historical `nlevels`
        // bug (unlike e.g. `toupper`/`nchar`, which std.R now does give a
        // `.default`, precisely because this lint caught them missing one).
        let findings = lint_generic_stub_names(&["crossprod".to_string()], "", false);
        assert_eq!(findings.len(), 1);
        assert!(findings[0].is_error());
    }

    #[test]
    fn nlevels_is_fine_because_std_r_already_ships_its_default() {
        // Regression guard for the historical bug: std.R must keep defining
        // `nlevels.default`, or this collision reopens silently.
        assert!(STD_R.contains("nlevels.default"));
        let findings = lint_generic_stub_names(&["nlevels".to_string()], "", false);
        assert!(findings.is_empty());
    }

    #[test]
    fn plain_generic_base_function_with_default_is_ok() {
        // `print` is S3-generic in base R and already has a base `.default`.
        let findings = lint_generic_stub_names(&["print".to_string()], "", false);
        assert!(findings.is_empty());
    }

    #[test]
    fn s4_generic_is_a_warning_not_strict() {
        let findings = lint_generic_stub_names(&["show".to_string()], "", false);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, LintSeverity::Warning);
    }

    #[test]
    fn s4_generic_is_an_error_under_strict() {
        let findings = lint_generic_stub_names(&["show".to_string()], "", true);
        assert_eq!(findings.len(), 1);
        assert!(findings[0].is_error());
    }

    #[test]
    fn unknown_name_is_not_flagged() {
        let findings = lint_generic_stub_names(&["totally_made_up_name".to_string()], "", false);
        assert!(findings.is_empty());
    }

    #[test]
    fn record_constructor_colliding_with_s4_class_is_a_warning() {
        // `factor` is a built-in S4 class name in the base R class table.
        let findings = lint_record_constructor_names(&["factor".to_string()]);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].severity, LintSeverity::Warning);
    }

    #[test]
    fn record_constructor_with_ordinary_name_is_fine() {
        let findings = lint_record_constructor_names(&["Point".to_string()]);
        assert!(findings.is_empty());
    }

    #[test]
    fn db_loads_and_is_nonempty() {
        let db = load_db();
        assert!(db.names.len() > 1000);
        assert!(!db.s4_classes.is_empty());
    }
}
