//! Cache of R name metadata, persisted as `.typr_cache/r_names.json`.
//!
//! For every R function name typr may collide with, the cache records the
//! three facts the build pipeline needs: is it S3-generic, is it S4-generic,
//! and does a `<name>.default` method already exist. `typr build` emits a
//! `name <- function(x, ...) UseMethod('name', x)` stub for every typed
//! function name (see `Context::get_all_generic_functions`); when the name it
//! shadows is a *plain* R function, that stub strands the original
//! implementation and every call fails at runtime with "no applicable method"
//! (the historical `nlevels` bug). Knowing a name is not S3-generic is what
//! lets the build generate `name.default <- function(...) pkg::name(...)`
//! alongside the stub instead.
//!
//! # Why a cache and not a static table
//!
//! The base-R half of this data is committed as `configs/src/r_name_db.json`
//! (generated by `tools/gen_r_name_db.R`) and embedded in the binary, but it
//! can only ever describe base/stats/utils/methods. A project that imports
//! `dplyr::filter` needs the same facts about `dplyr`, which are only knowable
//! on the machine where that package is installed. So the embedded table is a
//! *seed*: the first build copies it into `.typr_cache/r_names.json`, and
//! every build afterwards enriches it by introspecting (once per package) the
//! packages the project actually names. Because installed packages change
//! under the cache's feet, it is invalidatable: `typr cache refresh [pkg...]`
//! re-introspects, `typr cache clear` drops it back to the seed.
//!
//! Every read path is fail-open: a missing, unreadable, or unparsable cache
//! file simply means "fall back to the seed", never a build failure.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::cache::CACHE_DIR;

/// The committed base-R table, used to seed a fresh cache.
const SEED_JSON: &str = include_str!("../configs/src/r_name_db.json");
/// The introspection script run against packages the seed does not cover.
/// Also the backbone of `typr gen-types` (see `crate::gen_types`), which reads
/// this same script's `F`/`P` lines (formals, package version) alongside the
/// `N`/`V`/`C`/`E` lines this cache consumes.
pub(crate) const INTROSPECT_R: &str = include_str!("../configs/src/introspect_pkg.R");

pub const CACHE_FILE: &str = "r_names.json";

/// Bump when the on-disk layout changes so stale caches are ignored.
pub const R_NAMES_CACHE_VERSION: u32 = 1;

/// Packages covered by the embedded seed — never re-introspected.
const SEED_PACKAGES: &[&str] = &["base", "stats", "utils", "methods"];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RNameEntry {
    /// Package the name is exported from.
    pub pkg: String,
    /// Body dispatches through `UseMethod`, or the name is an S3 primitive
    /// generic. A stub over such a name is harmless: it already dispatches.
    pub s3_generic: bool,
    /// Known S4 generic — shadowing it masks S4 dispatch for packages
    /// attached later in the same session.
    pub s4_generic: bool,
    /// A `<name>.default` method already exists, so a `UseMethod` stub has
    /// somewhere to land without typr generating anything.
    pub has_default: bool,
}

impl RNameEntry {
    /// Whether shadowing this name with a bare `UseMethod` stub would strand
    /// its implementation: not reachable through *either* object system, and
    /// no default method to fall back on.
    pub fn needs_generated_default(&self) -> bool {
        !self.s3_generic && !self.s4_generic && !self.has_default
    }
}

/// Shape of the embedded seed file (`r_name_db.json`), which predates the
/// cache and carries no version or package list of its own.
#[derive(Debug, Deserialize)]
struct SeedDb {
    r_version: String,
    names: BTreeMap<String, RNameEntry>,
    s4_classes: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RNameCache {
    /// Layout version; a mismatch makes the whole file be ignored.
    #[serde(default)]
    pub cache_version: u32,
    /// R version the entries were last collected from: the seed's recorded
    /// version until an introspection on this machine supersedes it.
    pub r_version: String,
    /// Name → dispatch facts, ordered so the file stays diff-stable.
    pub names: BTreeMap<String, RNameEntry>,
    /// Known S4 class names, used by the record-constructor lint.
    pub s4_classes: BTreeSet<String>,
    /// Packages already introspected — the memo that keeps a build from
    /// re-spawning Rscript for a package it has already seen.
    #[serde(default)]
    pub packages: BTreeSet<String>,
    /// Packages Rscript could not load. Remembered so a missing package does
    /// not cost one failed subprocess per build; `refresh` clears them.
    #[serde(default)]
    pub failed_packages: BTreeSet<String>,
    /// Set when entries changed in memory and the file needs rewriting.
    #[serde(skip)]
    dirty: bool,
}

impl RNameCache {
    /// The cache as shipped: base/stats/utils/methods, no project packages.
    pub fn seed() -> Self {
        let seed: SeedDb = serde_json::from_str(SEED_JSON)
            .expect("configs/src/r_name_db.json is malformed — regenerate via tools/gen_r_name_db.R");
        RNameCache {
            cache_version: R_NAMES_CACHE_VERSION,
            r_version: seed.r_version,
            names: seed.names,
            s4_classes: seed.s4_classes.into_iter().collect(),
            packages: SEED_PACKAGES.iter().map(|p| p.to_string()).collect(),
            failed_packages: BTreeSet::new(),
            dirty: true,
        }
    }

    pub fn path(root: &Path) -> PathBuf {
        root.join(CACHE_DIR).join(CACHE_FILE)
    }

    /// Load the project's cache, falling back to the seed whenever the file is
    /// absent, unreadable, malformed, or written by an older layout.
    pub fn load(root: &Path) -> Self {
        let path = Self::path(root);
        let Ok(text) = fs::read_to_string(&path) else {
            return Self::seed();
        };
        match serde_json::from_str::<RNameCache>(&text) {
            Ok(cache) if cache.cache_version == R_NAMES_CACHE_VERSION => cache,
            _ => Self::seed(),
        }
    }

    /// Write the cache back if anything changed. Failures are silent by
    /// design: a cache that cannot be written only costs the next build an
    /// extra introspection, and must never break a build.
    pub fn save(&self, root: &Path) -> io::Result<()> {
        if !self.dirty {
            return Ok(());
        }
        let path = Self::path(root);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, serde_json::to_string_pretty(self)?)
    }

    /// Delete the persisted cache. The next build re-seeds from the embedded
    /// table and re-introspects the project's packages.
    pub fn clear(root: &Path) -> io::Result<()> {
        let path = Self::path(root);
        match fs::remove_file(&path) {
            Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
            other => other,
        }
    }
}

/// The cache's read API — the questions the build, the lint, and
/// `typr cache show` ask of it. These belong together as one surface, so the
/// block opts out of dead-code warnings rather than being pruned down to
/// whichever accessors the binary happens to call today.
#[allow(dead_code)]
impl RNameCache {
    pub fn lookup(&self, name: &str) -> Option<&RNameEntry> {
        self.names.get(name)
    }

    pub fn knows(&self, name: &str) -> bool {
        self.names.contains_key(name)
    }

    /// `None` when the name is unknown to the cache — the caller must not read
    /// that as "false": an unknown name is one we have no facts about.
    pub fn is_s3_generic(&self, name: &str) -> Option<bool> {
        self.lookup(name).map(|e| e.s3_generic)
    }

    pub fn is_s4_generic(&self, name: &str) -> Option<bool> {
        self.lookup(name).map(|e| e.s4_generic)
    }

    pub fn has_default(&self, name: &str) -> Option<bool> {
        self.lookup(name).map(|e| e.has_default)
    }

    pub fn package_of(&self, name: &str) -> Option<&str> {
        self.lookup(name).map(|e| e.pkg.as_str())
    }

    pub fn is_s4_class(&self, name: &str) -> bool {
        self.s4_classes.contains(name)
    }

    pub fn knows_package(&self, pkg: &str) -> bool {
        self.packages.contains(pkg)
    }

    /// Whether `pkg` is one of the R packages the embedded seed covers, i.e.
    /// part of every R installation rather than something the user chose to
    /// depend on. Forwarding a name to one of these is the deliberate
    /// `max`/`base::max` pattern; forwarding to a package the user merely
    /// happens to import is a coincidence, not an intent.
    pub fn is_seed_package(&self, pkg: &str) -> bool {
        SEED_PACKAGES.contains(&pkg)
    }
}

impl RNameCache {
    /// Introspect every package in `pkgs` the cache has not seen yet, merging
    /// the result in. Returns human-readable notes about packages that could
    /// not be loaded. Packages already known — or already known to be
    /// unloadable — cost nothing; a build that names only such packages spawns
    /// no subprocess at all.
    pub fn ensure_packages(&mut self, pkgs: &[String]) -> Vec<String> {
        let missing: Vec<String> = pkgs
            .iter()
            .filter(|p| !self.packages.contains(*p) && !self.failed_packages.contains(*p))
            .cloned()
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect();
        if missing.is_empty() {
            return Vec::new();
        }
        self.introspect_into(&missing)
    }

    /// Re-introspect `pkgs` (or every package the cache holds beyond the seed
    /// when empty), discarding what is already known about them first.
    pub fn refresh(&mut self, pkgs: &[String]) -> Vec<String> {
        let targets: Vec<String> = if pkgs.is_empty() {
            self.packages
                .iter()
                .filter(|p| !SEED_PACKAGES.contains(&p.as_str()))
                .chain(self.failed_packages.iter())
                .cloned()
                .collect()
        } else {
            pkgs.to_vec()
        };
        for pkg in &targets {
            self.names.retain(|_, e| &e.pkg != pkg);
            self.packages.remove(pkg);
            self.failed_packages.remove(pkg);
        }
        self.dirty = true;
        if targets.is_empty() {
            return Vec::new();
        }
        self.introspect_into(&targets)
    }

    /// Run the introspection script over `pkgs` and merge its output.
    ///
    /// Seed entries win over introspected ones: a name exported by both base
    /// and a package keeps its base facts, matching what R itself resolves for
    /// an unqualified call when the package is attached before base is
    /// searched.
    fn introspect_into(&mut self, pkgs: &[String]) -> Vec<String> {
        let output = match run_introspection(pkgs) {
            Ok(out) => out,
            Err(e) => {
                // No R on this machine, or the script could not run: remember
                // nothing, warn once, and let the build continue unaided.
                return vec![format!(
                    "could not introspect R package(s) {}: {e}. \
                     Names from those packages stay unknown to typr; \
                     run `typr cache refresh` once R is available.",
                    pkgs.join(", ")
                )];
            }
        };

        let mut notes = Vec::new();
        let mut loaded: BTreeSet<String> = BTreeSet::new();
        for line in output.lines() {
            let mut fields = line.split('\t');
            match fields.next() {
                Some("N") => {
                    let (Some(name), Some(pkg), Some(s3), Some(s4), Some(def)) = (
                        fields.next(),
                        fields.next(),
                        fields.next(),
                        fields.next(),
                        fields.next(),
                    ) else {
                        continue;
                    };
                    loaded.insert(pkg.to_string());
                    self.names.entry(name.to_string()).or_insert(RNameEntry {
                        pkg: pkg.to_string(),
                        s3_generic: s3 == "1",
                        s4_generic: s4 == "1",
                        has_default: def == "1",
                    });
                }
                Some("C") => {
                    if let Some(class) = fields.next() {
                        self.s4_classes.insert(class.to_string());
                    }
                }
                Some("V") => {
                    // The R that actually answered. It supersedes the seed's
                    // recorded version, which is whoever ran
                    // tools/gen_r_name_db.R, not this machine.
                    if let Some(version) = fields.next() {
                        self.r_version = version.to_string();
                    }
                }
                Some("E") => {
                    if let Some(pkg) = fields.next() {
                        let reason = fields.next().unwrap_or("unknown reason");
                        self.failed_packages.insert(pkg.to_string());
                        notes.push(format!("R package `{pkg}` could not be introspected ({reason})"));
                    }
                }
                _ => {}
            }
        }
        // A package that loaded but exports nothing typr cares about still
        // counts as seen, or every build would re-introspect it.
        for pkg in pkgs {
            if !self.failed_packages.contains(pkg) {
                self.packages.insert(pkg.clone());
            }
        }
        self.packages.extend(loaded);
        self.dirty = true;
        notes
    }
}

/// Spawn `Rscript introspect_pkg.R <pkgs...>` and return its stdout.
fn run_introspection(pkgs: &[String]) -> Result<String, String> {
    let script = std::env::temp_dir().join(format!("typr_introspect_{}.R", std::process::id()));
    fs::write(&script, INTROSPECT_R).map_err(|e| format!("cannot write introspection script: {e}"))?;
    let result = Command::new("Rscript").arg(&script).args(pkgs).output();
    let _ = fs::remove_file(&script);
    let output = result.map_err(|e| format!("Rscript could not be run ({e})"))?;
    if !output.status.success() {
        return Err(format!(
            "Rscript exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_loads_and_covers_base_r() {
        let cache = RNameCache::seed();
        assert!(cache.names.len() > 1000);
        assert!(!cache.s4_classes.is_empty());
        assert!(cache.knows_package("base"));
        // `print` is S3-generic in base R; `nlevels` is the historical plain one.
        assert_eq!(cache.is_s3_generic("print"), Some(true));
        assert_eq!(cache.is_s3_generic("nlevels"), Some(false));
        assert_eq!(cache.package_of("nlevels"), Some("base"));
    }

    #[test]
    fn unknown_name_is_none_not_false() {
        let cache = RNameCache::seed();
        assert_eq!(cache.is_s3_generic("totally_made_up_name"), None);
        assert!(!cache.knows("totally_made_up_name"));
    }

    #[test]
    fn needs_generated_default_is_the_nlevels_shape() {
        let cache = RNameCache::seed();
        // `nlevels`: plain base function, no `.default` in base itself.
        assert!(cache.lookup("nlevels").unwrap().needs_generated_default());
        // `print`: already dispatches, nothing to generate.
        assert!(!cache.lookup("print").unwrap().needs_generated_default());
    }

    #[test]
    fn load_falls_back_to_seed_when_no_file() {
        let dir = std::env::temp_dir().join(format!("typr_rname_empty_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let cache = RNameCache::load(&dir);
        assert!(cache.knows("nlevels"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn save_then_load_round_trips_added_entries() {
        let dir = std::env::temp_dir().join(format!("typr_rname_rt_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let mut cache = RNameCache::seed();
        cache.names.insert(
            "made_up_pkg_fn".to_string(),
            RNameEntry {
                pkg: "madeup".to_string(),
                s3_generic: false,
                s4_generic: false,
                has_default: false,
            },
        );
        cache.packages.insert("madeup".to_string());
        cache.save(&dir).unwrap();

        let reloaded = RNameCache::load(&dir);
        assert_eq!(reloaded.package_of("made_up_pkg_fn"), Some("madeup"));
        assert!(reloaded.knows_package("madeup"));

        RNameCache::clear(&dir).unwrap();
        assert!(!RNameCache::path(&dir).exists());
        // Clearing a cache that is already gone is not an error.
        RNameCache::clear(&dir).unwrap();
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn ensure_packages_is_a_noop_for_already_known_packages() {
        let mut cache = RNameCache::seed();
        // base is in the seed: no subprocess, no notes.
        let notes = cache.ensure_packages(&["base".to_string()]);
        assert!(notes.is_empty());
    }

    #[test]
    fn refresh_drops_the_packages_entries_first() {
        let mut cache = RNameCache::seed();
        cache.names.insert(
            "made_up_pkg_fn".to_string(),
            RNameEntry {
                pkg: "madeup".to_string(),
                s3_generic: false,
                s4_generic: false,
                has_default: false,
            },
        );
        cache.packages.insert("madeup".to_string());
        // Refreshing a package that is not installed drops what we knew and
        // records the failure rather than keeping stale facts around.
        cache.refresh(&["madeup".to_string()]);
        assert!(!cache.knows("made_up_pkg_fn"));
        assert!(!cache.knows_package("madeup"));
    }
}
